sudo: false
language: python
matrix:
  include:
    - python: 2.7
    - python: 3.7
      dist: xenial
      sudo: true
branches:
    only:
        - master
cache:
 - apt
 - pip
install: pip install tox-travis
script: tox
