# maquinitas.py
# by aaron montoya-moraga
# january 3rd 2018
# v0.0.1

name = "maquinitas"

RolandTR08 = {  "bdTune": 20,
                "bdTone": 21,
                "bdComp": 22,
                "bdDecay": 23,
                "bdLevel": 24,
                "sdTone": 25,
                "sdSnappy": 26,
                "sdComp": 27,
                "sdDecay": 28,
                "sdLevel": 29,
                "ltTune": 46,
                "ltDecay": 47,
                "ltLevel": 48,
                "mtTune": 49,
                "mtDecay": 50,
                "mtLevel": 51,
                "htTune": 52,
                "htDecay": 53,
                "htLevel": 54,
                "rsTune": 55,
                "rsDecay": 56,
                "rsLevel": 57,
                "cpTune": 58,
                "cpDecay": 59,
                "cpLevel": 60,
                "chTune": 61,
                "chDecay": 62,
                "chLevel": 63,
                "accent": 71,
                "ohTune": 80,
                "ohDecay": 81,
                "ohLevel": 82,
                "cyTune": 83,
                "cyDecay": 840,
                "cyLevel": 85,
                "cbTune": 86,
                "cbDecay": 87,
                "cbLevel": 88
                }

RolandSH01A = { "modulation": 1,
                "lfoRate": 3,
                "portamentoTime": 5,
                "expressionPedal": 11,
                "lfoWaveform": 12,
                "vcoModDepth": 13,
                "vcoRange": 14,
                "vcoPulseWidth": 15,
                "vcoPwmSource": 16,
                "vcoModSens": 17,
                "vcoBendDepth": 18,
                "vcoPwmLevel": 19,
                "vcoSawLevel": 20,
                "vcoSubLevel": 21,
                "vcoSubType": 22,
                "vcoNoiseLevel": 23,
                "vcfEnvDepth": 24,
                "vcfModDepth": 25,
                "vcfKeyFollow": 26,
                "vcfBendDepth": 27,
                "vcaEnvSw": 28,
                "vcaEnvMode": 29,
                "envSustain": 30,
                "portamentMode": 31,
                "hold": 64,
                "portamento": 65,
                "vcfResonance": 71,
                "envRelease": 72,
                "envAttack": 73,
                "vcfCutoff": 74,
                "envDecay": 75,
                "tune": 76,
                "transposeSw": 77,
                "noiseMode": 78,
                "lfoMode": 79,
                "assignMode": 80,
                "chordVoice2Sw": 81,
                "chordVoice3Sw": 82,
                "chordVoice4Sw": 83,
                "chordVoice2KeyShift": 85,
                "chordVoice3KeyShift": 86,
                "chordVoice4KeyShift": 87
                }
