---

"$schema": http://json-schema.org/draft-04/schema#
type: object
required:
  - environment
  - services
  - proxy
  - project_name
  - uid
  - gid
  - network-block
  - subnet
additionalProperties: false
properties:
  environment:
    type: string
    title: Environment, will be passed as env variable

  services:
    type: object
    additionalProperties: false
    properties:
      portainer:
        type: object
        properties:
          enabled: { type: boolean }
          version: { type: [string, number] }
          ram: { type: string }
          name: { type: string }
          service_name: { type: string }
          service_url: { type: string }
        required: [enabled, version, ram, service_name, service_url]

  proxy:
    type: object
    properties:
      enabled: { type: boolean }
      domain: { type: string }
      port: { type: integer }
    required: [enabled, domain, port]

  project_name:
    type: string
    title: Project name, must be the same name as root dir. Detected by default

  uid:
    title: Detected, by default uid of current user
  gid:
    title: Detected, by default gid of current user

  network-block:
    type: object
    properties:
      php:
        type: array
        items: { type: integer }

  subnet:
    type: string
