# Generated by Django 2.0 on 2018-01-11 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alipay', '0003_alipaypayment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alipaypayment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
