# Generated by Django 2.0.1 on 2018-07-19 10:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alipay', '0006_alipaypayment_buyer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='alipaypayment',
            name='expire',
            field=models.CharField(default='15m', max_length=10),
        ),
        migrations.AddField(
            model_name='alipaypayment',
            name='must_pay_before',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
