server:
  listen_host: 127.0.0.1
  listen_port: 5432

application:
  mounted_apps: []
  authnz_provider: morpfw.auth.authz:NullPolicy
  authn_storage: sqlstorage
  authn_storage_opts: {}
  new_user_state: active
  dburi: 'sqlite:///%(here)s/app.db'
  compositekey_separator: '!!!!'
  authn_policy: morpfw.auth.policy.noauth:AuthnPolicy
  development_mode: true

worker:
  enabled: false
  celery_settings: {}

security:
  allowed_nets:
    - 127.0.0.1/32

jwtauth:
  master_secret: secret
  leeway: 10
  allow_refresh: true

