logging:
    version: 1

    formatters:
      brief:
        format: '%(message)s'
      default:
        format: '[%(asctime)s.%(msecs)03d] %(levelname)-8s | %(name)-15s | %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'
      fluent_fmt:
        '()': fluent.handler.FluentRecordFormatter
        format:
          level: '%(levelname)s'
          hostname: '%(hostname)s'
          where: '%(module)s.%(funcName)s'
          time: '%(asctime)s'
          message: '%(message)s'

    handlers:
        console:
            class : logging.StreamHandler
            level: DEBUG
            formatter: default
            stream: ext://sys.stdout
        fluent:
            class: fluent.handler.FluentHandler
            host: 10.1.1.245
            port: 24224
            tag: fluentd.justpith.server
            buffer_overflow_handler: overflow_handler
            formatter: fluent_fmt
            level: DEBUG
        controller:
            class: fluent.handler.FluentHandler
            host: 10.1.1.245
            port: 24224
            tag: fluentd.justpith.controller
            buffer_overflow_handler: overflow_handler
            formatter: fluent_fmt
            level: DEBUG
        server:
            class: fluent.handler.FluentHandler
            host: 10.1.1.245
            port: 24224
            tag: fluentd.justpith.server
            buffer_overflow_handler: overflow_handler
            formatter: fluent_fmt
            level: DEBUG
        parser:
            class: fluent.handler.FluentHandler
            host: 10.1.1.245
            port: 24224
            tag: fluentd.justpith.parser
            buffer_overflow_handler: overflow_handler
            formatter: fluent_fmt
            level: DEBUG
        rss_consumer:
            class: fluent.handler.FluentHandler
            host: 10.1.1.245
            port: 24224
            tag: fluentd.justpith.rss_consumer
            buffer_overflow_handler: overflow_handler
            formatter: fluent_fmt
            level: DEBUG
        teacher:
            class: fluent.handler.FluentHandler
            host: 10.1.1.245
            port: 24224
            tag: fluentd.justpith.teacher
            buffer_overflow_handler: overflow_handler
            formatter: fluent_fmt
            level: DEBUG
        teacher_consumer:
            class: fluent.handler.FluentHandler
            host: 10.1.1.245
            port: 24224
            tag: fluentd.justpith.teacher_consumer
            buffer_overflow_handler: overflow_handler
            formatter: fluent_fmt
            level: DEBUG
        reccomender:
            class: fluent.handler.FluentHandler
            host: 10.1.1.245
            port: 24224
            tag: fluentd.justpith.reccomender
            buffer_overflow_handler: overflow_handler
            formatter: fluent_fmt
            level: DEBUG
        reccomender_consumer:
            class: fluent.handler.FluentHandler
            host: 10.1.1.245
            port: 24224
            tag: fluentd.justpith.reccomender_consumer
            buffer_overflow_handler: overflow_handler
            formatter: fluent_fmt
            level: DEBUG
        news_consumer:
            class: fluent.handler.FluentHandler
            host: 10.1.1.245
            port: 24224
            tag: fluentd.justpith.news_consumer
            buffer_overflow_handler: overflow_handler
            formatter: fluent_fmt
            level: DEBUG
        controller_consumer:
            class: fluent.handler.FluentHandler
            host: 10.1.1.245
            port: 24224
            tag: fluentd.justpith.controller_consumer
            buffer_overflow_handler: overflow_handler
            formatter: fluent_fmt
            level: DEBUG
        matrix:
            class: fluent.handler.FluentHandler
            host: 10.1.1.245
            port: 24224
            tag: fluentd.justpith.matrix
            buffer_overflow_handler: overflow_handler
            formatter: fluent_fmt
            level: DEBUG
        watcher:
            class: fluent.handler.FluentHandler
            host: 10.1.1.245
            port: 24224
            tag: fluentd.justpith.watcher
            buffer_overflow_handler: overflow_handler
            formatter: fluent_fmt
            level: DEBUG
        amazon_consumer:
            class: fluent.handler.FluentHandler
            host: 10.1.1.245
            port: 24224
            tag: fluentd.justpith.amazon_consumer
            buffer_overflow_handler: overflow_handler
            formatter: fluent_fmt
            level: DEBUG
        skyscanner_consumer:
            class: fluent.handler.FluentHandler
            host: 10.1.1.245
            port: 24224
            tag: fluentd.justpith.skyscanner_consumer
            buffer_overflow_handler: overflow_handler
            formatter: fluent_fmt
            level: DEBUG
        shopping_consumer:
            class: fluent.handler.FluentHandler
            host: 10.1.1.245
            port: 24224
            tag: fluentd.justpith.shopping_consumer
            buffer_overflow_handler: overflow_handler
            formatter: fluent_fmt
            level: DEBUG
        travel_consumer:
            class: fluent.handler.FluentHandler
            host: 10.1.1.245
            port: 24224
            tag: fluentd.justpith.travel_consumer
            buffer_overflow_handler: overflow_handler
            formatter: fluent_fmt
            level: DEBUG
        mio_cugino:
            class: fluent.handler.FluentHandler
            host: 10.1.1.245
            port: 24224
            tag: fluentd.justpith.mio_cugino
            buffer_overflow_handler: overflow_handler
            formatter: fluent_fmt
            level: DEBUG
        metric:
            class: fluent.handler.FluentHandler
            host: 10.1.1.245
            port: 24224
            tag: fluentd.justpith.metric
            buffer_overflow_handler: overflow_handler
            formatter: fluent_fmt
            level: DEBUG
        chat:
            class: fluent.handler.FluentHandler
            host: 10.1.1.245
            port: 24224
            tag: fluentd.justpith.chat
            buffer_overflow_handler: overflow_handler
            formatter: fluent_fmt
            level: DEBUG
        none:
            class: logging.NullHandler

    loggers:
        amqp:
            handlers: [none]
            propagate: False
        conf:
            handlers: [none]
            propagate: False
        'fluent.test': # root logger
            handlers: [console, fluent]
            level: DEBUG
            propagate: False
        'controller':
            handlers: [console, controller]
            level: DEBUG
            propagate: False
        'server':
            handlers: [console, server]
            level: DEBUG
            propagate: False
        'parser':
            handlers: [console, parser]
            level: DEBUG
            propagate: False
        'rss_consumer':
            handlers: [console, rss_consumer]
            level: DEBUG
            propagate: False
        'teacher': #
            handlers: [console, teacher]
            level: DEBUG
            propagate: False
        'teacher_consumer':
            handlers: [console, teacher_consumer]
            level: DEBUG
            propagate: False
        'reccomender':
            handlers: [console, reccomender]
            level: DEBUG
            propagate: False
        'reccomender_consumer':
            handlers: [console, reccomender_consumer]
            level: DEBUG
            propagate: False
        'news_consumer':
            handlers: [console, news_consumer]
            level: DEBUG
            propagate: False
        'controller_consumer':
            handlers: [console, controller_consumer]
            level: DEBUG
            propagate: False
        'matrix':
            handlers: [console, matrix]
            level: DEBUG
            propagate: False
        'watcher':
            handlers: [console, watcher]
            level: DEBUG
            propagate: False
        'amazon_consumer':
            handlers: [console, amazon_consumer]
            level: DEBUG
            propagate: False
        'skyscanner_consumer':
            handlers: [console, skyscanner_consumer]
            level: DEBUG
            propagate: False
        'shopping_consumer':
            handlers: [console, shopping_consumer]
            level: DEBUG
            propagate: False
        'travel_consumer':
            handlers: [console, travel_consumer]
            level: DEBUG
            propagate: False
        'mio_cugino':
            handlers: [console, mio_cugino]
            level: DEBUG
            propagate: False
        'metric':
            handlers: [console, metric]
            level: DEBUG
            propagate: False
        'chat':
            handlers: [console, chat]
            level: DEBUG
            propagate: False
