[tool.poetry]
name = "jrpytorch"
version = "0.1.0"
description = ""
authors = ["Jamie <jamie@jumpingrivers.com>"]

[tool.poetry.dependencies]
python = "^3.6"
numpy = "^1.15"
torch = "^1.0"
sklearn = "^0.0.0"
torchvision = "^0.2.1"
matplotlib = "^3.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
