import os
os.environ['FREESURFER_HOME'] = os.getcwd()
from qsiprep.workflows.base import init_qsiprep_wf
wf = init_qsiprep_wf(subject_list=['qsipreptest'],
                      task_id='',
                      run_uuid='X',
                      work_dir='.',
                      output_dir='.',
                      bids_dir='.',
                      ignore=[],
                      debug=False,
                      low_mem=False,
                      anat_only=False,
                      longitudinal=False,
                      freesurfer=False,
                      hires=False,
                      denoise_before_combining=True,
                      dwi_denoise_window=7,
                      combine_all_dwis=True,
                      omp_nthreads=1,
                      skull_strip_template='OASIS',
                      skull_strip_fixed_seed=False,
                      output_spaces=['T1w', 'template'],
                      template='MNI152NLin2009cAsym',
                      motion_corr_to='iterative',
                      b0_to_t1w_transform='Rigid',
                      hmc_transform='Affine',
                      impute_slice_threshold=0,
                      write_local_bvecs=False,
                      prefer_dedicated_fmaps=False,
                      fmap_bspline=False,
                      fmap_demean=True,
                      use_syn=True,
                      force_syn=True)