class EkkoPropertyNames:
    TS3_SERVER_HOST = 'EKKO_TS3_SERVER_HOST'
    TS3_SERVER_PORT = 'EKKO_TS3_SERVER_PORT'
    TS3_USERNAME = 'EKKO_TS3_USERNAME'
    TS3_IDENTITY = 'EKKO_TS3_IDENTITY'
    TS3_UNIQUE_ID = 'EKKO_TS3_UNIQUEID'
    TS3_CLIENT_APIKEY = 'EKKO_TS3_CLIENT_APIKEY'
    TS3_CHANNEL_NAME = 'EKKO_TS3_CHANNEL_NAME'
    TS3_CHANNEL_ID = 'EKKO_TS3_CHANNEL_ID'
    TS3_CHANNEL_PASSWORD = 'EKKO_TS3_CHANNEL_PASSWORD'
    TS3_SERVER_PASSWORD = 'EKKO_TS3_SERVER_PASSWORD'
    TS3_SERVER_PERMISSION_TOKEN = 'EKKO_TS3_SERVER_PERMISSION_TOKEN'

    EKKO_NODE_ID = 'EKKO_NODE_ID'

    TS3_CONFIG_DIRECTORY = 'EKKO_TS3_CONFIG_DIRECTORY'
    TS3_IDENTITY_DATABASE_PRECONF = 'EKKO_TS3_IDENTITY_DATABASE_PRECONF'
    TS3_IDENTITY_DATABASE_KEY = 'EKKO_TS3_IDENTITY_DATABASE_KEY'

    TS3_CLIENTQUERY_HOST = 'EKKO_TS3_CLIENTQUERY_HOST'
    TS3_CLIENTQUERY_PORT = 'EKKO_TS3_CLIENTQUERY_PORT'

    EKKO_CLIENT_CONTROL_PORT = 'EKKO_CLIENT_CONTROL_PORT'
    EKKO_MANAGE_SERVER = 'EKKO_MANAGE_SERVER'
    EKKO_MANAGE_PORT = 'EKKO_MANAGE_PORT'

    TS3_DIRECTORY = 'EKKO_TS3_DIRECTORY'
    TS3_RUNSCRIPT = 'EKKO_TS3_RUNSCRIPT'

    EKKO_MEDIA_DIRECTORY_SOURCE = 'EKKO_MEDIA_DIRECTORY_SOURCE'
    EKKO_MEDIA_DIRECTORY = 'EKKO_MEDIA_DIRECTORY'
    DOCKER_EKKO_CLIENT_BUILD = 'EKKO_DOCKER_EKKOCLIENT_BUILD'
    DOCKER_EKKO_CLIENT_DIRECTORY = 'EKKO_DOCKER_EKKOCLIENT_DIRECTORY'
    DOCKER_EKKO_CLIENT_IMAGE_NAME = 'EKKO_DOCKER_EKKOCLIENT_IMAGE_NAME'
    DOCKER_EKKO_CLIENT_IMAGE_TAG = 'EKKO_DOCKER_EKKOCLIENT_IMAGE_TAG'

    DOCKER_DISABLE_AUTOREMOVE = 'EKKO_DOCKER_DISABLE_AUTOREMOVE'
    DOCKER_NETWORK_NAME = 'EKKO_DOCKER_NETWORK_NAME'
    DOCKER_NETWORK_DBLINK = 'EKKO_DOCKER_NETWORK_DBLINK'

    DB_USERNAME = 'EKKO_DB_USERNAME'
    DB_HOST = 'EKKO_DB_HOST'
    DB_PASSWORD = 'EKKO_DB_PASSWORD'
    DB_DBNAME = 'EKKO_DB_DBNAME'

    EKKO_PERMISSION_PATH = 'EKKO_PERMISSION_PATH'
    EKKO_FIXTURES_PATH = 'EKKO_FIXTURES_PATH'

    LOG_LEVEL = 'EKKO_LOG_LEVEL'
    LOG_FORMAT = 'EKKO_LOG_FORMAT'

    COG_MEDIA_VOLUME_MODIFIER = 'EKKO_COG_MEDIA_VOLUME_MODIFIER'
    COG_MEDIA_VOLUME_MAX = 'EKKO_COG_MEDIA_VOLUME_MAX'
    COG_MEDIA_ALIAS_PREFIX = 'EKKO_COG_MEDIA_ALIAS_PREFIX'
