# Config file for automatic testing at travis-ci.org

language: python
python:
    - "3.6"

install:
    - pip install -r requirements.txt coverage python-coveralls
    - python setup.py --quiet install

script:
    - python setup.py test

after_success:
    - coverage run --source metrics tests.py
    - coveralls
