# Initial set of jobs that will be extended over time as
# we get things working.
- project:
    templates:
      - integrated-gate-py35
      - publish-openstack-docs-pti
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
    check:
      jobs:
        - openstack-tox-functional
        - openstack-tox-functional-py35
        - openstack-tox-functional-py36
        - placement-perfload:
            voting: false
    gate:
      jobs:
        - openstack-tox-functional
        - openstack-tox-functional-py35
        - openstack-tox-functional-py36

- job:
    name: placement-perfload
    parent: base
    description: |
        A simple node on which to run placement with the barest of configs and
        make performance related tests against it.
    required-projects:
        - git.openstack.org/openstack/placement
    run: playbooks/perfload.yaml
    post-run: playbooks/post.yaml
