# coding: utf-8

"""
    Nucleus API

    BETA version of the nucleus text analytics API.  # noqa: E501

    OpenAPI spec version: v0.1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import nucleus_api
from nucleus_api.models.meta_data import MetaData  # noqa: E501
from nucleus_api.rest import ApiException


class TestMetaData(unittest.TestCase):
    """MetaData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetaData(self):
        """Test MetaData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = nucleus_api.models.meta_data.MetaData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
