# This file automatically generated by
#    C:\Jenkins\workspace\python\python-scripted-build-pipeline\couchbase-python-client\couchbase_version.py
# at
#    2019-01-08 17:04:23.971626
__version__ = '2.5.3'