[tool.poetry]
name = "is_git_repo_clean"
version = "0.3.0"
description = "A simple function to test whether your git repo is clean"
authors = ["Philip Olson <philip.olson@pm.me>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
