---
- job:
    name: kolla-ansible-base
    pre-run: tests/pre.yml
    run: tests/run.yml
    post-run: tests/post.yml
    attempts: 1
    timeout: 7200
    required-projects:
      - openstack/kolla
      - openstack/kolla-ansible
      - openstack/requirements
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*
      - ^test-requirements.txt$
      - ^releasenotes/.*$
    vars:
      scenario: aio
      enable_core_openstack: yes
    roles:
      - zuul: openstack-infra/zuul-jobs

- job:
    name: kolla-ansible-bifrost-base
    parent: kolla-ansible-base
    vars:
      scenario: bifrost
      install_type: source
      enable_core_openstack: no
