---
- project:
    templates:
      - check-requirements
      - deploy-guide-jobs
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - kolla-ansible-centos-source
        - kolla-ansible-ubuntu-source
        - kolla-ansible-oraclelinux-source
        - kolla-ansible-ubuntu-source-ceph
        - kolla-ansible-centos-source-ceph
        - kolla-ansible-oraclelinux-source-ceph
        - kolla-ansible-bifrost-centos-source:
            files: ^ansible\/roles\/bifrost\/.*
        - kolla-ansible-ubuntu-source-zun:
            files: ^ansible\/roles\/zun\/.*
        - kolla-ansible-centos-source-scenario-nfv:
            files: ^ansible\/roles\/(barbican|heat|mistral|redis|tacker)\/.*
    gate:
      jobs:
        - kolla-ansible-centos-source
        - kolla-ansible-ubuntu-source
    periodic:
      jobs:
        - kolla-ansible-bifrost-centos-source
        - kolla-ansible-ubuntu-source-zun
        - kolla-ansible-centos-source-scenario-nfv
