[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "pypath-setup"
version = "0.1.3"
description = "Start processes by setting PYTHONPATH to point to some virtualenv"
authors = ["Paul Maréchal <marechap.info@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
"pypath-setup" = "pypath_setup:main"
