BUFFER_SIZE = 4096
TIMEOUT = 0.05

DEFAULT_SERVER_IP = '127.0.0.1'
DEFAULT_CLIENT_IP = '94.16.123.171'
DEFAULT_PORT = 12345

BEGIN_MSG = 'BEGIN:MSG:'
END_MSG = ':END:MSG'
BEGIN_FILE = 'BEGIN:FILE:'
END_FILE = ':END:FILE'

TYPE_MSG = 'MSG'
TYPE_FILE = 'FILE'

ERROR = 'ERROR'
INTERRUPT = 'INTERRUPT'

NAME_CHANGE = 'NAMECHANGE:'
INIT_CLIENT = 'INITCLIENT:'

DEFAULT_DIR = 'tmp/'
DEFAULT_CLIENT_NAME = 'Pymmel'
