[tool.poetry]
name = "confedit"
version = "0.1.1"
description = ""
authors = ["Dominic Looser <dominic.looser@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.0"
pick = "^0.6.4"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[tool.poetry.scripts]
conf = 'confedit:conf'
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

