---

environment: dev

services:
  portainer:
    enabled: false
    version: latest
    ram: 512M
    service_name: Portainer (Docker Webadmin)
    service_url: http://{}
proxy:
  enabled: true
  domain: localhost
  port: 80

project_name: ''

network-block:
  php: [25, 465, 587]

subnet: ''

uid:
gid:
