
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-01-09T13:14:49-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "b4d399c28d21dc144b2067e0f0fd7537b530295c",
 "version": "1.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
