repos:
- repo: https://github.com/asottile/seed-isort-config
  rev: v1.2.0
  hooks:
  - id: seed-isort-config
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.4
  hooks:
  - id: isort
- repo: https://github.com/ambv/black
  rev: 18.6b4
  hooks:
  - id: black
    args: [--safe, --quiet]
    language_version: python3.6
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: debug-statements
  - id: flake8
- repo: https://github.com/asottile/pyupgrade
  rev: v1.4.0
  hooks:
  - id: pyupgrade
