sudo: false
cache: pip
language: python
python:
  - 3.6
  - 3.5
stages:
  - lint
  - docs
  - test
env:
  - TOXENV=py
  - TOXENV=doctest
jobs:
  include:
    # lint stage
    - stage: lint
      env: TOXENV=manifest
    - env: TOXENV=flake8
    - env: TOXENV=pyroma
    - env: TOXENV=xenon
    - env: TOXENV=mypy
    # docs stage
    - stage: docs
      env: TOXENV=doc8
    - env: TOXENV=readme
    # tests stage gets propagated automatically
install:
  - sh -c 'if [ "$TOXENV" = "py" ]; then pip install tox codecov coverage; else pip install tox; fi'
script:
  - tox
after_success:
  - sh -c 'if [ "$TOXENV" = "py" ]; then tox -e coverage-report; codecov; fi'
