language: python
python:
  - "2.7"
  - "3.6"
cache: pip
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq gfortran
install:
  - pip install -r requirements-travis.txt
script:
  - python setup.py build
  - python setup.py install
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/55cf16b611593edcb09d
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
