[tool.poetry]
name = "getup"
version = "0.0.10"
description = "Projectless Django setup tool"
authors = ["Jussi Arpalahti <jussi.arpalahti@gmail.com>"]
license = "MPL-2.0"
readme = 'README.md'
repository = "https://gitlab.com/jussiarpalahti/getup"

[tool.poetry.dependencies]
python = "^3.7"
django = "^2.1"
black = { version = "*", allows-prereleases = true }
django-environ = "^0.4.5"


[tool.poetry.dev-dependencies]
pytest = "^3.0"

[tool.poetry.scripts]
getup = "getup.getup:main"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

