
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-01-06T10:20:51-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "2de77aa57d2173c74eaefda0429a7b07a3085f1b",
 "version": "1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
