package:
   name: intake-spark
   version: {{ GIT_DESCRIBE_TAG }}

source:
   path: ..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - jinja2
  run:
    - intake>=0.2
    - python
    - pyspark

test:
  source_files:
    - tests
  requires:
    - pytest
    - pytest-cov
    - coverage
  commands:
    - py.test --verbose --cov=intake_spark tests

about:
  home: https://github.com/ContinuumIO/intake-spark
  license: BSD
  license_file: LICENSE
  summary: |
    Apache Spark plugin for Intake
