dist: trusty
sudo: false
language: python
python:
- '3.6'
cache:
  pip: true
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/bundles/*"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
- provider: pypi
  user: adafruit-travis
  on:
    tags: true
  password:
    secure: i2xGWp0KznggKBXodgUiYTPDW2qw5rJ/luL7WCtJozMDm72x5xErjSmXCbOKymiv8TPg0Ds6Ifr0gaykPd4GIx76UN7SS3xzAaqQqYp9c+6xqQFwgWDOj9TLC/0fRVALD1Ek2J+HeFNWzLapkOLFnHZzFdrkOrKGIM5YMy8gitypnB/oNVNc28Jk0S3/LDkbe927oCpn0rizRP115WiZFKQIKDzmZpqWLBZXtcAHqEhe3hNOtO45D/zIPoa2ubDfbKGfnJcvmj3PNgSlt/QagqGDNclmXt9Lqwcw/8cdUncDP6MJh28M5zFzPDOdJaZNK+SAhaGHq4UTHx9hQGnhpgjf77KbkVuWHQEjQJI4FJcUwTpYBXtieiSqSVtcmi5npk9JIEeyyRqegeA2WpDd7X+IOPm3gcLWKd5rdNGC1GqrWi5Ko2Xd/ChUUllz/UMx/yxnUwqpj71tYSXfZZesEPwp0SICHEWoEevLX0Yb1i90ug+Obha7tGaP7WaF6g5BDCt8TZtJS90QSDZdNul2L8vh/ipwAdVw07FQK4v+hFaGaCRLi/3o7H/1aT3GNKOP1GlCMFck9txDw52Xl9NhJGYVIqJyYsRf9p8lc4Ln1K0N5X8mrGSDdPlWU1bY7m0ta7DwUV2A5zzcNnyRThM+dsdAJqkJh2Fes5X1EgzOA2Y=
install:
- pip install -r requirements.txt
- pip install pylint circuitpython-build-tools Sphinx sphinx-rtd-theme
- pip install --force-reinstall pylint==1.9.2
script:
- pylint adafruit_matrixkeypad.py
- ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name,bad-whitespace
  examples/*.py)
- circuitpython-build-bundles --filename_prefix adafruit-circuitpython-matrixkeypad
  --library_location .
- cd docs && sphinx-build -E -W -b html . _build/html && cd ..
