# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/travis/build/randovania/randovania/randovania/gui/data_editor.ui',
# licensing of '/home/travis/build/randovania/randovania/randovania/gui/data_editor.ui' applies.
#
# Created: Thu Dec 27 13:19:08 2018
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_DataEditorWindow(object):
    def setupUi(self, DataEditorWindow):
        DataEditorWindow.setObjectName("DataEditorWindow")
        DataEditorWindow.resize(802, 471)
        self.centralWidget = QtWidgets.QWidget(DataEditorWindow)
        self.centralWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.worldSelectorBox = QtWidgets.QComboBox(self.groupBox)
        self.worldSelectorBox.setObjectName("worldSelectorBox")
        self.horizontalLayout.addWidget(self.worldSelectorBox)
        self.areaSelectorBox = QtWidgets.QComboBox(self.groupBox)
        self.areaSelectorBox.setEnabled(False)
        self.areaSelectorBox.setObjectName("areaSelectorBox")
        self.horizontalLayout.addWidget(self.areaSelectorBox)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 2)
        self.pointOfInterestBox = QtWidgets.QGroupBox(self.centralWidget)
        self.pointOfInterestBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.pointOfInterestBox.setTitle("")
        self.pointOfInterestBox.setObjectName("pointOfInterestBox")
        self.gridLayout = QtWidgets.QGridLayout(self.pointOfInterestBox)
        self.gridLayout.setObjectName("gridLayout")
        self.pointOfInterestScrollArea = QtWidgets.QScrollArea(self.pointOfInterestBox)
        self.pointOfInterestScrollArea.setWidgetResizable(True)
        self.pointOfInterestScrollArea.setObjectName("pointOfInterestScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 274, 320))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pointOfInterestScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.pointOfInterestScrollArea, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.pointOfInterestBox, 1, 0, 2, 1)
        self.nodeInfoBox = QtWidgets.QGroupBox(self.centralWidget)
        self.nodeInfoBox.setObjectName("nodeInfoBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.nodeInfoBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.nodeHealsBox = QtWidgets.QCheckBox(self.nodeInfoBox)
        self.nodeHealsBox.setObjectName("nodeHealsBox")
        self.horizontalLayout_2.addWidget(self.nodeHealsBox)
        self.gridLayout_2.addWidget(self.nodeInfoBox, 1, 1, 1, 1)
        self.connectionsBox = QtWidgets.QGroupBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectionsBox.sizePolicy().hasHeightForWidth())
        self.connectionsBox.setSizePolicy(sizePolicy)
        self.connectionsBox.setMinimumSize(QtCore.QSize(0, 0))
        self.connectionsBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.connectionsBox.setObjectName("connectionsBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.connectionsBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.otherNodeConnectionBox = QtWidgets.QComboBox(self.connectionsBox)
        self.otherNodeConnectionBox.setEnabled(False)
        self.otherNodeConnectionBox.setObjectName("otherNodeConnectionBox")
        self.verticalLayout_2.addWidget(self.otherNodeConnectionBox)
        self.other_node_alternatives_scroll_area = QtWidgets.QScrollArea(self.connectionsBox)
        self.other_node_alternatives_scroll_area.setLineWidth(4)
        self.other_node_alternatives_scroll_area.setWidgetResizable(True)
        self.other_node_alternatives_scroll_area.setObjectName("other_node_alternatives_scroll_area")
        self.other_node_alternatives_contents = QtWidgets.QWidget()
        self.other_node_alternatives_contents.setGeometry(QtCore.QRect(0, 0, 452, 225))
        self.other_node_alternatives_contents.setObjectName("other_node_alternatives_contents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.other_node_alternatives_contents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.other_node_alternatives_scroll_area.setWidget(self.other_node_alternatives_contents)
        self.verticalLayout_2.addWidget(self.other_node_alternatives_scroll_area)
        self.gridLayout_2.addWidget(self.connectionsBox, 2, 1, 1, 1)
        DataEditorWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(DataEditorWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 802, 21))
        self.menuBar.setObjectName("menuBar")
        DataEditorWindow.setMenuBar(self.menuBar)

        self.retranslateUi(DataEditorWindow)
        QtCore.QMetaObject.connectSlotsByName(DataEditorWindow)

    def retranslateUi(self, DataEditorWindow):
        DataEditorWindow.setWindowTitle(QtWidgets.QApplication.translate("DataEditorWindow", "Data Visualizer", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("DataEditorWindow", "World/Area Selection", None, -1))
        self.nodeInfoBox.setTitle(QtWidgets.QApplication.translate("DataEditorWindow", "Node Info", None, -1))
        self.nodeHealsBox.setText(QtWidgets.QApplication.translate("DataEditorWindow", "Heals?", None, -1))
        self.connectionsBox.setTitle(QtWidgets.QApplication.translate("DataEditorWindow", "Connections", None, -1))

