dist: xenial
sudo: false
language: python

python:
- 2.7
- 3.6
- &latest_py3 3.7

jobs:
  fast_finish: true
  include:
  - stage: deploy
    if: tag IS present
    python: *latest_py3
    before_script: skip
    env:
    - TWINE_USERNAME=jaraco
    # TWINE_PASSWORD
    - secure: TBLgrksohR7FfDvabU8aST+qKV0zl3pyTWsmKnkJqGo8+rltNKm+Ggt6B0jxO7LWm1TqhhtG+b+h4Rf1hm4ynL7q7/eNkJVnZlQGoyWiXVOVrC6ZT/RRlqam8s7C4iMY2H/Y9YYen2HSGYYZ5AP2M+Z6dEOKEDg8a7J2uEM9cxl3mfMhc/VF+qvWbskIGbZS6g+qNOuLUlSyaljN2oqVFPndLeuOyyPg/Yw1p4QB1rRZySL8DTohkmiDy1ReXIrtvU8OL1HyAbfJg7C7cGXeDHqV4OwhOqsBhDQNOIPHw+JC9/ieEop1uRe6g3+Ew7vphx8IrKG4FuSwl9hFSo/ah0+E3HcZuk+j8ZqeohjySR4DWzXYfO1G2vdbCX1WLUNGpA9/vwFuQKoBbQHK1uAj7VNobKPBPL+AWjD5XHnUqTsr9OVy/woxdFKQODPKJzoVLeBN8PdztKWWMCXxCiVZfLTc1kJZX21HnJ6EV8lkd3vkJ1OKq6Tm3qJPliAOheFN/iIqPyzY+LaW1qm+RPtBYpg1srCPRXjDIOOZyCREoLRkyu/fEFAI3PC/GdD8IagqyvhNGxU8atkm/oyKu3alAh+yMNqDYJpO+c6M3uf3Y2f0wcLt9srcyIEB+uwfyeNvOGWYGBZ6T10wYDnO5eE47Wvqj+FAEBj7iqxJ2w54GJc=
    - TOX_TESTENV_PASSENV="TWINE_USERNAME TWINE_PASSWORD"
    script: tox -e release

cache: pip

install:
- pip install tox tox-venv

before_script:
  # Disable IPv6. Ref travis-ci/travis-ci#8361
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
    fi
script: tox
