language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27

install:
  - pip install pylint pep8

before_script:
  - pylint --version

script: 
  - pylint remotsylib/*.py
  - python setup.py bdist


notifications:
  email:
    on_success: never
    on_failure: change
