repos:
- repo: https://github.com/asottile/reorder_python_imports
  rev: v1.3.3
  hooks:
  - id: reorder-python-imports

- repo: https://github.com/grktsh/ffffff
  rev: v2018.11.4
  hooks:
  - id: ffffff

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.0.0
  hooks:
  - id: end-of-file-fixer
  - id: flake8
  - id: trailing-whitespace
