---
data_interface_base:
  type: "string"
  required: True
  empty: False

data_interface_offset:
  type: "integer"
  required: True
  default: 0

max_data_interfaces:
  type: "integer"
  required: True
  default: 0

management_interface:
  type: "string"
  required: True
  empty: True

reserved_interfaces:
  type: "integer"
  default: 0

internal_interfaces:
  type: "integer"
  default: 0