# https://aka.ms/yaml
jobs:
- job: WinTest
  pool:
    vmImage: vs2017-win2016
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
    maxParallel: 3

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
#
#  - task: CondaEnvironment@1
#    inputs:
#      createCustomEnvironment: True
#      environmentName: blpenv
#      packageSpecs: 'python=3.6'
#      # updateConda: # Optional
#      # installOptions: blpapi
#      createOptions: -c conda-forge blpapi
#      # cleanEnvironment: # Optional
#      architecture: 'x64'

#  - script: |
#      conda create --yes --quiet --name blp_env python=%PYTHON_VERSION% blpapi
#      source activate blp_env
#    displayName: Create Anaconda environment

  - script: |
      python -m pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    displayName: Install prerequisites

  - script: |
      python -m pip install flake8
      flake8 --extend-ignore=E701,E501 xbbg
    displayName: Run Lint Tests

  - script: |
      pip install pytest pytest-cov coverage codecov
      pytest xbbg --doctest-module --cov -v
      codecov --token=ff17768d-30bd-4917-98f2-a011606597ea
    displayName: Run Doctests and Coverages
