__title__ = 'multitranslator'
__description__ = 'Multi translation engine for Python'
__url__ = 'https://github.com/GreatBahram/multitranslator'
__version__ = '0.0.2'
__author__ = 'Bahram Aghaei'
__author_email__ = 'aghaee.bahram@gmail.com'
__license__ = 'GNU General Public License v3.0'
