# Contains all of the processing parameters
# Note that this configuration file will be imported after the shared parameters config
# For more, see overwatch.base.config
#
# author: Raymond Ehlers <raymond.ehlers@cern.ch>, Yale University
# date: 16 July 2018

# Force each run to be reprinted and regenerate the pages.
forceReprocessing: false

# Select particular run numbers to be reprocessed
forceReprocessRuns: []

# Force the subsystem to be recreated during processing.
# This will allow the applied functions to be re-determined
forceRecreateSubsystem: false

# Force each run to be re-merged.
# Note that this can change the merging if new information has arrived since the last merge.
forceNewMerge: False

# Set the type of merging based on the data we are receiving. If set to true, that means we are receiving
# cumulative files (i.e. the hists are not reset after they are sent by the HLT). In that case,
# to do a partial merge we take the last run file and subtract it from the first. 
cumulativeMode: True

# Specifies the prefix necessary to get to all of the folders.
# Don't include a trailing slash! (This may be mitigated by os.path calls, but not worth the
# risk in changing it).
dirPrefix: *dataFolder

# Can be ignored during development!
# Time to sleep (in seconds) between executing the processing. A value <= 0 will ensure
# that the processing is only executed once. The repeated execution is used for deployment.
processingTimeToSleep: -1
