[tool.poetry]
name = "speiseplan"
version = "0.1.0"
description = ""
authors = ["Markus Quade <markus.quade@gmail.com>"]
license = "MIT"

[tool.poetry.scripts]
speiseplan = "speiseplan:main"

[tool.poetry.dependencies]
python = "^3.7"
selenium-requests-html = "^1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
