[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "ScanLHA"
author = "Martin Gabelmann"
author-email = "martin@gabelmann.biz"
home-page = "https://github.com/martingabelmann/ScanLHA"
classifiers = ["License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)"]
requires = [
    "pylha",
    "numpy",
    "ipython",
    "tqdm",
    "pandas",
    "matplotlib",
    "PyYAML",
]
description-file = "README.md"

[tool.flit.scripts]
ScanLHA      = "ScanLHA.ScanLHA:ScanLHA"
PlotLHA      = "ScanLHA.PlotLHA:Plot"
EditLHA      = "ScanLHA.EditLHA:Edit"
MergeLHA     = "ScanLHA.MergeLHA:Merge"
