[tool.poetry]
name = "opensoundscape"
version = "0.1.0"
description = "Open source, scalable acoustic classification for ecology and conservation"
authors = [
    "Barry Moore <moore0557@gmail.com>",
    "Justin Kitzes <justin.kitzes@pitt.edu>",
    "Tessa Rhinehart <tessa.rhinehart@gmail.com>"
]

[tool.poetry.dependencies]
python = "^3.7"
docopt = "^0.6.2"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
black = "18.9b0"
pre-commit = "^1.14"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
opensoundscape = "opensoundscape.console:run"
