[tool.poetry]
name = "chatql"
version = "0.1.1"
readme = "README.md"
authors = ["katsugeneration <katsu.generation.888@gmail.com>"]
homepage = "https://github.com/katsugeneration"
repository = "https://github.com/katsugeneration/chatql"

[tool.poetry.dependencies]
python = "^3.6"
graphene = "^2.1"
mongoengine = "^0.16.3"
flask = {version = "^1.0",extras = ["server"]}
line-bot-sdk = {version = "^1.8",extras = ["line"]}

[tool.poetry.dev-dependencies]
pytest = "^3.0"
nose = "^1.3"
tox = "^3.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
