sudo: true

language: python

matrix:
    include:
        - os: linux
          sudo: true
          python: 3.7
          dist: xenial
        - os: linux
          sudo: required
          python: 3.6
        - os: linux
          sudo: required
          python: 3.5
        - os: linux
          sudo: required
          python: 3.4
        - os: linux
          sudo: required
          python: 2.7
        - os: osx
          language: generic
          env: TOXENV=py36
        - os: osx
          language: generic
          env: TOXENV=py35
        - os: osx
          language: generic
          env: TOXENV=py34
        - os: osx
          language: generic
          env: TOXENV=py27

install:
  - pip install -r dev-requirements.txt
  - python setup.py install

script:
  - python -m pytest pycm/ --cov=pycm --cov-report=term
  - python version_check.py
  - python -m cProfile -s cumtime pycm/pycm_profile.py
after_success:
  - codecov