[tool.poetry]
name = "stylo"
version = "0.9.3"
description = "Drawing images with a blend of Python and Mathematics"
readme = "README.md"

authors = ["Alex Carney <alcarneyme@gmail.com>"]

license = "MIT"

homepage = "https://stylo.readthedocs.io/en/latest/"
repository = "https://github.com/alcarney/stylo"
documentation = "https://stylo.readthedocs.io/en/latest/"

classifiers = [
    "Development Status :: 3 - Alpha",
    "Topic :: Multimedia :: Graphics"
]

include = ["CHANGES.rst"]

[tool.poetry.dependencies]
python = "^3.5"

numpy = "*"
Pillow = "*"
click = "*"

# TODO: Click has a progress bar, use that instead.
tqdm = "*"

hypothesis = { version = "^3.*", optional = true}
pytest = {version = "4.0.2", optional = true}
matplotlib = {version = "^3.*", optional = true}
jupyter = {version = "^1.0", optional = true}

[tool.poetry.extras]
testing = ["pytest", "hypothesis"]
jupyter = ["jupyter", "matplotlib"]

[tool.poetry.dev-dependencies]
pytest = "4.0.2"
pytest-cov = "^2.6"
hypothesis = "3.*"
sphinx = "^1.8"
sphinx-stylo = "^0.1.1"
topos-theme = "^0.0.11"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"


# vim: ft=dosini
