---
version: 1
disable_existing_loggers: False
formatters:
  default:
    format: "%(asctime)s %(levelname)-8s [%(name)s.%(funcName)s:%(lineno)d] %(message)s"
  colored:
    '()': 'colorlog.ColoredFormatter'
    format: "%(log_color)s%(asctime)s %(levelname)-8s [%(name)s.%(funcName)s:%(lineno)d] %(message)s"
    log_colors:
      DEBUG: white
      INFO: bold_white
      WARNING: yellow
      ERROR: red
      CRITICAL: bold_red
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: colored
    stream: ext://sys.stdout
root:
  level: DEBUG
  handlers: [console]
...
