language: python
dist: xenial
python:
  - "3.6"
  - "3.7"
services:
  - docker
before_install:
  - docker pull acroz/livy
  - docker run --publish 8998:8998 acroz/livy &
  - sleep 10
script:
  - pip install flake8 mypy black .
  - flake8
  - mypy . --ignore-missing-imports
  - black livy tests docs setup.py --check
  - python setup.py test
  - python setup.py it
