# Contains all of the DQM receiver parameters
# Note that this configuration file will be imported after the shared parameters config
# For more, see overwatch.base.config
#
# author: Raymond Ehlers <raymond.ehlers@cern.ch>, Yale University
# date: 16 July 2018

receiverIP: "127.0.0.1"
receiverPort: 8080

apiToken: "abcdefghi"
