dist: xenial
sudo: false
language: python

python:
- 2.7
- 3.6
- &latest_py3 3.7

jobs:
  fast_finish: true
  include:
  - stage: deploy
    if: tag IS present
    python: *latest_py3
    before_script: skip
    env:
    - TWINE_USERNAME=jaraco
    # TWINE_PASSWORD
    - secure: JPNyPOS343PTaD39/AD2tjR+VZPjVST23GSWKGZfORc7iSkmqXxsheeqRHZQvNbTvKWKJJf2do6FuZD6H2C7aPb1l9SOjRYXEenjIuwkHPpRRuIDYCN4JcvjaMKSTbzd5hlSV8LKnGyyDXUtlz0dX6Mgm/LatTYPrktohKoZuTC9asZeMG2cI6NZm0GGmmYsOnIekXwwV+A5C3UirSOVr1lkhBN5uIzqJd212YGR2+0t+CV1V9jfsAOn39WkXq/5kVjiI49AXJqgYOVi15ZOBxhbO3gDPMLeVxskL2TCAHKphuWFB9H4+C8e8vEPH2cdCS/iBGqwGli07/KPS8cWlcWCPqssEWESAPIUWdC9f7y15QXYHJUZ17alfiAdEidaPN98MXSEbmz7S+L8cWrjWVbuDyTZ14dir5x8hn3r5TcB7Libdrl1j/ysmHPjbdwF3aDc3OF4dhBJSWpoGG5Jtf6kbFcNxhoz2JZTjqbC+aY2DvZGsN7AeQUeSWkrh85JJANiPZEbprcmAMtStd/f6HSR5HFrVrGoBOWGAfwlYxMibLr9U8KnhvcTmmpHeEYdai9A3oJ/YuZBUNhFO7Ka9TDh2vk2EQ1MUAdO8Sn9jiTisduVIEyC2POfYIs0a5F98UqPsZruKgb5Fgvm3ifc6My9iWMii2PCbzmwaJS1cuw=
    - TOX_TESTENV_PASSENV="TWINE_USERNAME TWINE_PASSWORD"
    script: tox -e release

cache: pip

install:
- pip install tox tox-venv

before_script:
  # Disable IPv6. Ref travis-ci/travis-ci#8361
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
    fi
script: tox
