language: python

sudo: false

python:
  - '3.5'
  - '2.7'
  - '2.6'
  - '3.4'
  - '3.6'

install:
- pip install -e .
- pip install -r requirements-dev.txt

script:
- python ./setup.py develop && COMPILE='--compile' make check

# blacklist
branches:
  except:
    - data-driven-pytest
