[tool.poetry]
name = "is_git_repo_clean"
version = "0.3.1"
description = "A simple function to test whether your git repo is clean"
authors = ["Philip Olson <philip.olson@pm.me>"]
readme = "README.md"
repository = "https://github.com/olsonpm/py_is-git-repo-clean"
include = ["license.txt", "bin/*"]

[tool.poetry.scripts]
is-git-repo-clean = "is_git_repo_clean.script"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
