
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-01-05T21:09:45-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "8c3707398073fa273ba0ee9d027a48b447c8df57",
 "version": "0.31"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
