
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "d1033dd2afd0b19409b31a41e6743b9469a87e98",
 "version": "0.5.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
