[tool.poetry]
name = "dutch-workdays"
version = "0.2.0"
description = "A very small library that handles with Dutch calendars and holidays 🇳🇱"
readme = "README.rst"
authors = ["New10 <pypi-admin@new10.com>"]
homepage = "https://gitlab.com/new10-public/dutch-workdays/"
license = "MIT"
keywords = ['workdays', 'dutch', 'netherlands', 'calendar']

[tool.poetry.dependencies]
python = ">=3.6"

[tool.poetry.dev-dependencies]
black = {version = "^18.3-alpha.0",allows-prereleases = true}
pytest = "^4.1"
flake8 = "^3.6"
isort = "^4.3"
pre-commit = "^1.14"
mypy = "^0.660.0"
pytest-cov = "^2.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
