---
features:
  - |
    Added an option, haproxy_nova_serialconsole_proxy_tunnel_timeout,
    to configure the nova_serialconsole_proxy tunnel timeout. This default
    is to keep the websocket connection alive for 10 minutes.
