---
features:
  - |
    Support ansible check and diff module for generate configurations. You could
    use ``EXTRA_OPTS='--check --diff' kolla-ansible genconfig`` to check what
    the configuration file will be like in dry-run mode.
