---
guest_pairs:
  juniper/vmx:
    child: "juniper/vmx-vcp"
    parent: "juniper/vmx-vfp"

  juniper/vqfx:
    child: "juniper/vqfx-pfe"
    parent: "juniper/vqfx-re"

guest_config:
  arista/veos:
    data_interface_base: "eth"
    data_interface_offset: 1
    internal_interfaces: 0
    max_data_interfaces: 24
    management_interface: "ma1"
    reserved_interfaces: 0

  cisco/csr1000v:
    data_interface_base: "ge"
    data_interface_offset: 2
    internal_interfaces: 0
    max_data_interfaces: 25
    management_interface: "ge1"
    reserved_interfaces: 0

  cisco/iosv:
    data_interface_base: "ge0/"
    data_interface_offset: 1
    internal_interfaces: 0
    max_data_interfaces: 7
    management_interface: "ge0/0"
    reserved_interfaces: 0

  cisco/xrv:
    data_interface_base: "ge0/0/0/"
    data_interface_offset: 0
    internal_interfaces: 0
    max_data_interfaces: 96
    management_interface: "me0"
    reserved_interfaces: 0

  CumulusCommunity/cumulus-vx:
    data_interface_base: "swp"
    data_interface_offset: 1
    internal_interfaces: 0
    max_data_interfaces: 96
    management_interface: "eth0"
    reserved_interfaces: 0

  juniper/vmx-vcp:
    data_interface_base: "NA"
    data_interface_offset: 0
    internal_interfaces: 1
    max_data_interfaces: 0
    management_interface: "fxp0.0"
    reserved_interfaces: 0

  juniper/vmx-vfp:
    data_interface_base: "ge-0/0/"
    data_interface_offset: 0
    internal_interfaces: 1
    max_data_interfaces: 10
    management_interface: "ext"
    reserved_interfaces: 0

  juniper/vqfx-pfe:
    data_interface_base: "NA"
    data_interface_offset: 0
    internal_interfaces: 1
    max_data_interfaces: 0
    management_interface: "eth1"
    reserved_interfaces: 0

  juniper/vqfx-re:
    data_interface_base: "xe-0/0/"
    data_interface_offset: 0
    internal_interfaces: 1
    max_data_interfaces: 12
    management_interface: "em0.0"
    reserved_interfaces: 1

  juniper/vsrx:
    data_interface_base: "ge-0/0/"
    data_interface_offset: 0
    internal_interfaces: 0
    max_data_interfaces: 16
    management_interface: "fxp0.0"
    reserved_interfaces: 0

  juniper/vsrx-packetmode:
    data_interface_base: "ge-0/0/"
    data_interface_offset: 0
    internal_interfaces: 0
    max_data_interfaces: 16
    management_interface: "fxp0.0"
    reserved_interfaces: 0

  centos/7:
    data_interface_base: "eth"
    data_interface_offset: 1
    internal_interfaces: 0
    max_data_interfaces: 8
    management_interface: "eth0"
    reserved_interfaces: 0

  generic/ubuntu1804:
    data_interface_base: "eth"
    data_interface_offset: 1
    internal_interfaces: 0
    max_data_interfaces: 8
    management_interface: "eth0"
    reserved_interfaces: 0

  opensuse/openSUSE-15.0-x86_64:
    data_interface_base: "eth"
    data_interface_offset: 1
    internal_interfaces: 0
    max_data_interfaces: 8
    management_interface: "eth0"
    reserved_interfaces: 0

  unknown/unknown:
    data_interface_base: "int"
    data_interface_offset: 1
    internal_interfaces: 0
    max_data_interfaces: 8
    management_interface: "int0"
    reserved_interfaces: 0
