image: python:3.7-alpine

stages:
 - build
 - test
 - release

check:
  stage: build
  tags:
    - qa
  before_script:
    - pip install black flake8
  script:
    - black --check -v --diff $(find -name "*.py")
    - flake8 --max-line-length=88 .

package:
  stage: build
  only:
    - tags
  before_script:
    - apk add git
  script:
    - python setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist/
    expire_in: 1 day

.template_py: &template_py
  stage: test
  tags:
    - qa
  before_script:
    - apk add docker git
    - pip install pytest docker-compose tox

py27:
  <<: *template_py
  image: python:2.7-alpine
  script:
    - tox -e py27

py35:
  <<: *template_py
  image: python:3.5-alpine
  script:
    - tox -e py35

py36:
  <<: *template_py
  image: python:3.6-alpine
  script:
    - tox -e py36

py37:
  <<: *template_py
  image: python:3.7-alpine
  script:
    - tox -e py37

deploy:
  stage: release
  only:
    - tags
  before_script:
    - pip install twine
  script:
    - twine upload dist/*
  dependencies:
    - package
