
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "1cc46b35d1445c8a27c976b5d04043d8779e0d04",
 "version": "2050"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
