# Generated by Django 2.1.5 on 2019-01-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_log', '0009_auto_20190116_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='status',
            field=models.CharField(choices=[('W', 'Watched'), ('I', 'Ignored'), ('S', 'Skipped'), ('P', 'In Progress'), ('U', 'Unwatched')], default='U', max_length=1),
        ),
    ]
