repos:
-   repo: https://github.com/ambv/black
    rev: 18.6b4
    hooks:
    - id: black
      language_version: python3
-   repo: https://github.com/asottile/blacken-docs
    rev: v0.2.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==18.6b4]
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.5.0
    hooks:
    -   id: pyupgrade
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-ast
    -   id: mixed-line-ending
    -   id: debug-statements
    -   id: flake8
        additional_dependencies: [flake8-bugbear]
