sudo: required
language: python
python:
  - 3.4
  - 3.5
  - 3.6
services:
  - docker
before_install:
  - docker pull stepic/epicbox-python
install:
  - pip install -r requirements/dev.txt
script: py.test tests
