---
- include_tasks: register.yml
  when: inventory_hostname in groups['nova-api']

- include_tasks: bootstrap_xenapi.yml
  when:
    - inventory_hostname in groups['compute']
    - nova_compute_virt_type == "xenapi"

- include_tasks: config.yml

- include_tasks: config-nova-fake.yml
  when:
    - enable_nova_fake | bool
    - inventory_hostname in groups['compute']

- include_tasks: bootstrap.yml
  when: inventory_hostname in groups['nova-api'] or
        inventory_hostname in groups['compute']

- name: Flush handlers
  meta: flush_handlers

- include_tasks: simple_cell_setup.yml
