# Copyright 2018 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- project-template:
    name: kuryr-kubernetes-tempest-jobs
    check:
      jobs:
        - kuryr-kubernetes-tempest-octavia
        - kuryr-kubernetes-tempest-daemon-octavia
        - kuryr-kubernetes-tempest-daemon-openshift-octavia
        - kuryr-kubernetes-tempest-daemon-lbaasv2
        - kuryr-kubernetes-tempest-daemon-containerized-octavia
        - kuryr-kubernetes-tempest-daemon-containerized-ovn
        - kuryr-kubernetes-tempest-daemon-octavia-py36
        - kuryr-kubernetes-tempest-daemon-containerized-octavia-py36
        - kuryr-kubernetes-tempest-multinode-daemon-octavia-containerized
        - kuryr-kubernetes-tempest-octavia-centos-7
    gate:
      jobs:
        - kuryr-kubernetes-tempest-octavia
        - kuryr-kubernetes-tempest-daemon-octavia
        - kuryr-kubernetes-tempest-daemon-lbaasv2
        - kuryr-kubernetes-tempest-daemon-containerized-octavia
        - kuryr-kubernetes-tempest-daemon-octavia-py36
        - kuryr-kubernetes-tempest-daemon-containerized-octavia-py36
    experimental:
      jobs:
        - kuryr-kubernetes-tempest-dragonflow
        - kuryr-kubernetes-tempest-daemon-containerized-openshift-octavia
        - kuryr-kubernetes-tempest-daemon-containerized-octavia-l2
        - kuryr-kubernetes-tempest-daemon-containerized-octavia-pools-namespace
        - kuryr-kubernetes-tempest-daemon-containerized-octavia-network-policy
        - kuryr-kubernetes-tempest-daemon-containerized-openshift-octavia-serial
        - kuryr-kubernetes-tempest-daemon-ovn
        - kuryr-kubernetes-tempest-daemon-openshift-octavia-ingress
        - kuryr-kubernetes-tempest-daemon-openshift-octavia-multi-vif
        - kuryr-kubernetes-tempest-multinode-daemon-octavia-ha
        - kuryr-kubernetes-tempest-daemon-containerized-octavia-crio

- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - openstack-lower-constraints-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
      - check-requirements
      - kuryr-kubernetes-tempest-jobs
