[codestyle]
indent_type = 'space' # 'tab' or 'space'
indent_width = 4

## template_file is a file path to template code
#template_file=

## code_generator_file is a path to .py file defining custom code generator function.
## Please check README.md for details.
#code_generator_file=

[postprocess]
## exec_on_each_problem_dir is executed after every problem directory's creation
## with its problem directory as cwd like arc001/A
#exec_on_each_problem_dir='clang-format -i ./*.cpp'

## exec_on_contest_dir is executed once after `atcoder-tools gen`
## with the contest directory as cwd like arc001/
#exec_on_contest_dir=
