heat_template_version: rocky

description: >
  Fluentd client configured with Puppet.
  This service is deprecated and will be removed in future releases.

parameters:
  ServiceData:
    default: {}
    description: Dictionary packing service data
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  RoleName:
    default: ''
    description: Role name on which the service is applied
    type: string
  RoleParameters:
    default: {}
    description: Parameters specific to the role
    type: json
  EndpointMap:
    default: {}
    description: >
      Mapping of service endpoint -> protocol. Typically set
      via parameter_defaults in the resource registry.
    type: json

resources:

  LoggingConfiguration:
    type: OS::TripleO::LoggingConfiguration

outputs:
  role_data:
    description: Role data for the Fluentd client role.
    value:
      service_name: fluentd
      config_settings:
        fluentd::package_name: fluentd
        fluentd::service_name: fluentd
        fluentd::config_file: /etc/fluentd/fluent.conf
        fluentd::config_owner: fluentd
        fluentd::config_group: fluentd
        fluentd::config_path: /etc/fluentd/config.d
        fluentd::plugin_provider: yum
        fluentd::service_provider: systemd
        fluentd::repo_install: false
        tripleo::profile::base::logging::fluentd::fluentd_servers:
          get_attr: [LoggingConfiguration, LoggingServers]
        tripleo::profile::base::logging::fluentd::fluentd_default_format:
          get_attr: [LoggingConfiguration, LoggingDefaultFormat]
        tripleo::profile::base::logging::fluentd::fluentd_filters:
          yaql:
            expression: >
              $.data.filters.flatten().where($)
            data:
              filters:
                - get_attr: [LoggingConfiguration, LoggingDefaultFilters]
                - get_attr: [LoggingConfiguration, LoggingExtraFilters]
        tripleo::profile::base::logging::fluentd::fluentd_pos_file_path:
          get_attr: [LoggingConfiguration, LoggingPosFilePath]
        tripleo::profile::base::logging::fluentd::fluentd_use_ssl:
          get_attr: [LoggingConfiguration, LoggingUsesSSL]
        tripleo::profile::base::logging::fluentd::fluentd_ssl_certificate:
          get_attr: [LoggingConfiguration, LoggingSSLCertificate]
        tripleo::profile::base::logging::fluentd::fluentd_ssl_key:
          get_attr: [LoggingConfiguration, LoggingSSLKey]
        tripleo::profile::base::logging::fluentd::fluentd_ssl_key_passphrase:
          get_attr: [LoggingConfiguration, LoggingSSLKeyPassphrase]
        tripleo::profile::base::logging::fluentd::fluentd_shared_key:
          get_attr: [LoggingConfiguration, LoggingSharedKey]
      step_config: |
        include ::tripleo::profile::base::logging::fluentd
      upgrade_tasks: []
