checks:
  python:
    code_rating: true
    duplicate_code: true
    classes_valid_slots: true

build:
  environment:
    python: 3.6
  nodes:
    analysis:
      tests:
        override:
          - py-scrutinizer-run
    tests:
      tests:
        override:
          - true
filter:
  excluded_paths:
    - "*/test/*"
  dependency_paths:
    - "lib/*"
tools:
  external_code_coverage:
    # py27-cover,py34-cover,py35-cover,py36-cover,py37-cover,pypy-cover,pypy3-cover
    runs: 7
    # timeout in seconds, default 5 minutes
    timeout: 630
