stages:
    - test

before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - apt-get update -qy
    - apt-get install -y python-dev python-pip python3-dev python3-pip python-numpy python3-numpy g++

test:
    stage: test
    script:
        - bash tests/test_all.sh
