dist: trusty
sudo: false
language: python
python:
- '3.6'
cache:
  pip: true
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/bundles/*"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
- provider: pypi
  user: adafruit-travis
  on:
    tags: true
  password:
    secure: qBh2IbaYCvrW18r61zO6YjJp7DdOyVxMLYLlQljTSA1Fo8PZw8oxRV/LdkODzpP633vIEyawclLmnXV37gUGLunwZXguYs7XukWDBs42P0WWKeAXASZkqlh8Ue4E6OC5pyF4Qqh1jk19xE+2rrBJIronRslulCkc9EbU8HSTgs3TfVoM+JnTU7vv1auHYF+gmusI9mSiGpfNN4Xv3gju/+82OJel1S3lykB88vtQ4dwykz0nYe1gD0U27NVALocAo/XZLDlc3ppjtBp10uQWJjqYH1kKH129lO94myyu9uFgTV1nmUJgsM7Y6TVyhCmU9QcYEyiLv+fq9eNLI3S3iXYdPqUQGm7MhNpRdL00Qwtnc3NJXFtyCx9yptUqjUwI/RNCKonXI7w1RbpjZdBqIdmjE8K1xB/okqtrI8GhWPSaUnd1aVuGMCCC0+M27NBv+5MMXNw0CqXPCltq0zGC3hA9jsfJLwLUfhgfX5XqfusovmXvHA6lhzA2Y43jTvcfxUMcD/PpLytCiI9I0QlLxMIQVU2DQD2Kc8Hn7bcISwNGc9vweUXJrtr/nwsvB3kIYoPfiCrqKi0v/VPvJu/0bKPmcTZt5YUCTch+ZmwKJfmGXF323yLdEldB93br/g2DfmP47ym59+ln4S8nJnNQKtgkcGIBj3MDvCVIycNhvRE=
install:
- pip install -r requirements.txt
- pip install circuitpython-build-tools Sphinx sphinx-rtd-theme
- pip install --force-reinstall pylint==1.9.2
script:
- pylint adafruit_bluefruitspi.py
- ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name,bad-whitespace
  examples/*.py)
- circuitpython-build-bundles --filename_prefix adafruit-circuitpython-bluefruitspi
  --library_location .
- cd docs && sphinx-build -E -W -b html . _build/html && cd ..
