dist: xenial
sudo: false
language: python

python:
- 3.6
- &latest_py3 3.7

jobs:
  fast_finish: true
  include:
  - stage: deploy
    if: tag IS present
    python: *latest_py3
    before_script: skip
    env:
    - TWINE_USERNAME=jaraco
    # TWINE_PASSWORD
    - secure: Yrq0vI93rYhYrwo5/5f+moJ/iJ7buVlLWETYE/JoYuzkA/KvbGN2LyhVGpueIqsU0CpRH8Hdo8O37xBDE6qzgYSFEzrfgnoTyuw9wTfd/iInvnaDa2LsC3cBGWnp10+k/ngrQCnbBZNNhGY9X4flGUEjksYxcoD7Q0rnJEcVSIheFYYNoNAl3k22/zFE6Ivs2V33nG3yOqv2tgymf/e1SG68AnB/a/9MqYCb4pT7+pcyLbvn0SjdYX+Hk6QSYFYKLqr1aI9U4zD9VEgwbU8M8vQdtNarA7MbXmwnej+M+B3rL8bVVpKDu5TljG9+BdLnUKr1JtuaNYewqezZbP1DTf46bcK9MIqcbVdQo7i+ppcGL4qDgdI9lcGn+pmwTtOjX272ZuByIlwiP7v3SHDcZ+bROu6CxI4raX9tJVfCIdtIY4eYaqOpdzmT9pEjlrUM2SoOqa7pDxa3HmxpbVHsXWous+J2zBs+YI3rZgRfrfeMlGWFQvzooxcO0abJn9UmbElKedLz8pZXrG17oQG3uQk4QTbhcfo0v/lfWpsAonX38dmfMgC/Zkz/epBIyGDwfHrpc6z8Axc4MwfeJ/u/5hFVYsTsZDtKBKE6Emxf4F7NqYNlDyi/uY0czfvwmDwm9QolzL1FzswZRsZncKJyHttslWJ0ZQ1ovepsinY0K0w=
    - TOX_TESTENV_PASSENV="TWINE_USERNAME TWINE_PASSWORD"
    script: tox -e release

cache: pip

install:
- pip install tox tox-venv

before_script:
  # Disable IPv6. Ref travis-ci/travis-ci#8361
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
    fi
script: tox
