# Generated by Django 2.0 on 2018-03-31 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alipay', '0004_auto_20180111_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alipaypayment',
            name='status',
            field=models.CharField(choices=[('INIT', '已创建'), ('WAIT_BUYER_PAY', '等待付款'), ('TRADE_PENDING', '确认中'), ('TRADE_SUCCESS', '成功'), ('TRADE_CLOSED', '关闭'), ('TRADE_FINISHED', '完成'), ('MANUAL_SUCCESS', '手动成功')], default='INIT', max_length=20),
        ),
    ]
