
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-01-16T08:47:08-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "8e622851fe558ba7740427d88339f2b5e6debf83",
 "version": "v0.4.31"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
