[tool.poetry]
name = "fastest"
version = "0.0.3"
description = "Automate tests via docstrings and more"
authors = ["AmreshVenugopal <amresh.venugopal@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

packages = [
    { include="fastest", from="." },
]
