[tool.poetry]
name = "ldcv"
version = "1.0.1"
description = "LangMan Console Version"
authors = ["leetking <li_tking@163.com>"]
license = "GPL-3.0"
readme = "README.rst"
homepage = "https://github.com/leetking/ldcv"
repository = "https://github.com/leetking/ldcv"

[tool.poetry.dependencies]
python = "^3.0"
lxml = "^4.2"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
ldcv = 'ldcv:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
