version: '{branch}-{build}'
build: off
cache:
  - '%LOCALAPPDATA%\pip\Cache'
environment:
  matrix:
    - TOXENV: check
    - TOXENV: 'py27-t35-c44,py27-t35-c45,py27-t36-c44,py27-t36-c45,py27-t37-c44,py27-t37-c45'
    - TOXENV: 'py34-t35-c44,py34-t35-c45,py34-t36-c44,py34-t36-c45,py34-t37-c44,py34-t37-c45'
    - TOXENV: 'py35-t35-c44,py35-t35-c45,py35-t36-c44,py35-t36-c45,py35-t37-c44,py35-t37-c45'
    - TOXENV: 'pypy-t35-c44,pypy-t35-c45,pypy-t36-c44,pypy-t36-c45,pypy-t37-c44,pypy-t37-c45'

init:
  - ps: echo $env:TOXENV
  - ps: ls C:\Python*
install:
  # install pypy using choco (redirect to a file and write to console in case
  # choco install returns non-zero, because choco install python.pypy is too
  # noisy)
  - choco install python.pypy > pypy-inst.log 2>&1 || (type pypy-inst.log & exit /b 1)
  - set PATH=C:\tools\pypy\pypy;%PATH% # so tox can find pypy
  - echo PyPy installed
  - pypy --version

  - C:\Python35\python -m pip install tox

test_script:
  - C:\Python35\python -m tox

on_failure:
  - ps: dir "env:"
  - ps: get-content .tox\*\log\*
artifacts:
  - path: dist\*

### To enable remote debugging uncomment this (also, see: http://www.appveyor.com/docs/how-to/rdp-to-build-worker):
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
