language: python
python:
  - 2.7
  - 3.6
  - 3.7
sudo: false
dist: xenial
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
env:
  - DJANGO_VERSION=1.8.19 DB=SQLite
  - DJANGO_VERSION=1.11.17 DB=SQLite
  - DJANGO_VERSION=1.8.19 DB=Postgres
  - DJANGO_VERSION=1.11.17 DB=Postgres
services:
  – postgresql
addons:
  postgresql: '9.6'
install:
  - pip install -r requirements.txt
  - pip install -q flake8
  - pip install -q psycopg2
  - pip install -q  --pre Django==$DJANGO_VERSION
  - python setup.py install
before_script:
  - wget "http://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c 'create database robotframework;' -U postgres
  # - django-admin startproject mysite
script:
  - flake8 DjangoLibrary
  - py.test mysite
  - robot DjangoLibrary/tests/
