
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-01-15T23:57:32-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "c76fa657f449ad1bb96cf6ce3af82074ca6312dc",
 "version": "1.4.0a4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
