[tool.poetry]
name = "diecast"
version = "0.3.2"
description = "Dependency Injection framework for Python 3"
homepage = "https://glow.dev.maio.me/sjohnson/diecast"
repository = "https://glow.dev.maio.me/sjohnson/diecast"
keywords = ["dependency-injection", "di", "python3"]
authors = ["Sean Johnson <sean.johnson@maio.me>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.4"

[tool.poetry.dev-dependencies]
black = "^18.3-alpha.0"
flake8 = "^3.5"
pylint = "^2.1"
mypy = "^0.620.0"
pytest = "^3.8"
pytest-cov = "^2.6"

[tool.black]
line-length = 88
py36 = true
include = '\.pyi?$'
