- job:
    name: nodepool-zuul-functional
    parent: tox
    description: |
      Test that zuul works with current nodepool sources.

      This test runs the zuul project ``nodepool`` environment.
    pre-run: playbooks/nodepool-zuul-functional/pre.yaml
    post-run: playbooks/nodepool-zuul-functional/post.yaml
    required-projects:
      - openstack-infra/nodepool
      - openstack-infra/zuul
    vars:
      zuul_work_dir: "{{ zuul.projects['git.openstack.org/openstack-infra/zuul'].src_dir }}"
      tox_envlist: nodepool

# NOTE(ianw): this job doesn't really do anything unless you set
# "NODEPOOL_PAUSE_something_DIB: false" to unpause one or more builds.
- job:
    name: nodepool-functional-base
    parent: devstack
    # NOTE(ianw): for now, keep these jobs as Xenial only.  We will
    # add bionic variants, but we want to keep Xenial testing around
    # whilst we still run Xenial for upstream nodepool-builders too
    nodeset: openstack-single-node-xenial
    pre-run: playbooks/nodepool-functional-base/pre.yaml
    post-run: playbooks/nodepool-functional-base/post.yaml
    timeout: 5400
    required-projects:
      - openstack-infra/nodepool
    vars:
      devstack_localrc:
        USE_PYTHON3: True
      devstack_services:
        horizon: false
        ceilometer-acentral: false
        ceilometer-acompute: false
        ceilometer-alarm-evaluator: false
        ceilometer-alarm-notifier: false
        ceilometer-anotification: false
        ceilometer-api: false
        ceilometer-collector: false
        cinder: false
        c-bak: false
        c-sch: false
        c-api: false
        c-vol: false
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
        # Nodepool doesn't need vnc access
        n-novnc: false
        # Nodepool testing uses config drive only
        n-api-meta: false
        q-meta: false
      devstack_plugins:
        nodepool: https://git.openstack.org/openstack-infra/nodepool
      zuul_copy_output:
        '/var/log/nodepool/builds': 'logs'

- job:
    name: nodepool-functional-py35
    parent: nodepool-functional-base
    description: |
      Run nodepool functional tests for py35
    run: playbooks/nodepool-functional-py35/run.yaml
    vars:
      devstack_localrc:
        NODEPOOL_PAUSE_UBUNTU_XENIAL_DIB: false

- job:
    name: nodepool-functional-py35-src-base
    parent: nodepool-functional-base
    run: playbooks/nodepool-functional-py35-src/run.yaml
    required-projects:
      - openstack-infra/glean
      - openstack-infra/nodepool
      - openstack/diskimage-builder
      - openstack/openstacksdk

- job:
    name: nodepool-functional-py35-src
    parent: nodepool-functional-py35-src-base
    vars:
      devstack_localrc:
        NODEPOOL_PAUSE_UBUNTU_XENIAL_DIB: false

# Distro functional tests.  This is used by projects such as
# diskimage-builder and glean as live-boot tests
- job:
    name: nodepool-functional-py35-redhat-src
    parent: nodepool-functional-py35-src-base
    vars:
      devstack_localrc:
        NODEPOOL_PAUSE_CENTOS_7_DIB: false
        NODEPOOL_PAUSE_FEDORA_28_DIB: false

- job:
    name: nodepool-functional-py35-suse-src
    parent: nodepool-functional-py35-src-base
    vars:
      devstack_localrc:
        NODEPOOL_PAUSE_OPENSUSE_423_DIB: false
        NODEPOOL_PAUSE_OPENSUSE_150_DIB: false
        NODEPOOL_PAUSE_OPENSUSE_TUMBLEWEED_DIB: false

- job:
    name: nodepool-functional-py35-gentoo-src
    parent: nodepool-functional-py35-src-base
    vars:
      devstack_localrc:
        NODEPOOL_PAUSE_GENTOO_17_0_SYSTEMD_DIB: false

- job:
    name: nodepool-functional-py35-ubuntu-src
    parent: nodepool-functional-py35-src-base
    vars:
      devstack_localrc:
        NODEPOOL_PAUSE_UBUNTU_BIONIC_DIB: false
        NODEPOOL_PAUSE_UBUNTU_XENIAL_DIB: false
        NODEPOOL_PAUSE_UBUNTU_TRUSTY_DIB: false

- job:
    name: nodepool-functional-py35-debian-src
    parent: nodepool-functional-py35-src-base
    vars:
      devstack_localrc:
        NODEPOOL_PAUSE_DEBIAN_STRETCH_DIB: false

- job:
    description: |
      Test that nodepool works with kubernetes.
    name: nodepool-functional-k8s
    pre-run: playbooks/nodepool-functional-k8s/pre.yaml
    run: playbooks/nodepool-functional-k8s/run.yaml
    post-run: playbooks/nodepool-functional-k8s/post.yaml
    nodeset: ubuntu-xenial
    required-projects:
      - openstack-infra/nodepool

- project:
    check:
      jobs:
        - tox-docs
        - tox-pep8
        - tox-py35
        - tox-py36:
            nodeset: ubuntu-bionic
        - nodepool-zuul-functional:
            voting: false
        - nodepool-functional-py35:
            voting: false
        - nodepool-functional-py35-src:
            voting: false
        - nodepool-functional-k8s
        - pbrx-build-container-images:
            vars:
              pbrx_prefix: zuul
        - zuul-quick-start
    gate:
      jobs:
        - tox-docs
        - tox-pep8
        - tox-py35
        - tox-py36:
            nodeset: ubuntu-bionic
        - pbrx-build-container-images:
            vars:
              pbrx_prefix: zuul
        - zuul-quick-start
    post:
      jobs:
        - publish-zuul-docs
        - openstackzuul-pbrx-push-container-images:
            vars:
              pbrx_prefix: zuul

    experimental:
      jobs:
        - nodepool-functional-py35-debian-src
    release:
      jobs:
        - release-zuul-python
        - publish-zuul-docs
