/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.19.13
 *
 *     Copyright: (c) 2018 by Total Control Software
 *     License:   wxWindows License
 */

#include "sipAPI_html.h"

        #include <wx/html/htmlcell.h>

        #include <wx/colour.h>


class sipwxHtmlRenderingStyle : public  ::wxHtmlRenderingStyle
{
public:
    sipwxHtmlRenderingStyle();
    sipwxHtmlRenderingStyle(const  ::wxHtmlRenderingStyle&);
    virtual ~sipwxHtmlRenderingStyle();

    /*
     * There is a protected method for every virtual method visible from
     * this class.
     */
protected:
     ::wxColour GetSelectedTextBgColour(const  ::wxColour&);
     ::wxColour GetSelectedTextColour(const  ::wxColour&);

public:
    sipSimpleWrapper *sipPySelf;

private:
    sipwxHtmlRenderingStyle(const sipwxHtmlRenderingStyle &);
    sipwxHtmlRenderingStyle &operator = (const sipwxHtmlRenderingStyle &);

    char sipPyMethods[2];
};

sipwxHtmlRenderingStyle::sipwxHtmlRenderingStyle():  ::wxHtmlRenderingStyle(), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipwxHtmlRenderingStyle::sipwxHtmlRenderingStyle(const  ::wxHtmlRenderingStyle& a0):  ::wxHtmlRenderingStyle(a0), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipwxHtmlRenderingStyle::~sipwxHtmlRenderingStyle()
{
    sipInstanceDestroyedEx(&sipPySelf);
}

 ::wxColour sipwxHtmlRenderingStyle::GetSelectedTextBgColour(const  ::wxColour& clr)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[0],sipPySelf,sipName_HtmlRenderingStyle,sipName_GetSelectedTextBgColour);

    if (!sipMeth)
        return  ::wxColour();

    extern  ::wxColour sipVH__html_0(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, const  ::wxColour&);

    return sipVH__html_0(sipGILState, 0, sipPySelf, sipMeth, clr);
}

 ::wxColour sipwxHtmlRenderingStyle::GetSelectedTextColour(const  ::wxColour& clr)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[1],sipPySelf,sipName_HtmlRenderingStyle,sipName_GetSelectedTextColour);

    if (!sipMeth)
        return  ::wxColour();

    extern  ::wxColour sipVH__html_0(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, const  ::wxColour&);

    return sipVH__html_0(sipGILState, 0, sipPySelf, sipMeth, clr);
}


PyDoc_STRVAR(doc_wxHtmlRenderingStyle_GetSelectedTextColour, "GetSelectedTextColour(clr) -> wx.Colour\n"
"\n"
"Returns the colour to use for the selected text.");

extern "C" {static PyObject *meth_wxHtmlRenderingStyle_GetSelectedTextColour(PyObject *, PyObject *, PyObject *);}
static PyObject *meth_wxHtmlRenderingStyle_GetSelectedTextColour(PyObject *sipSelf, PyObject *sipArgs, PyObject *sipKwds)
{
    PyObject *sipParseErr = NULL;
    PyObject *sipOrigSelf = sipSelf;

    {
        const  ::wxColour* clr;
        int clrState = 0;
         ::wxHtmlRenderingStyle *sipCpp;

        static const char *sipKwdList[] = {
            sipName_clr,
        };

        if (sipParseKwdArgs(&sipParseErr, sipArgs, sipKwds, sipKwdList, NULL, "BJ1", &sipSelf, sipType_wxHtmlRenderingStyle, &sipCpp, sipType_wxColour, &clr, &clrState))
        {
             ::wxColour*sipRes;

            if (!sipOrigSelf)
            {
                sipAbstractMethod(sipName_HtmlRenderingStyle, sipName_GetSelectedTextColour);
                return NULL;
            }

            PyErr_Clear();

            Py_BEGIN_ALLOW_THREADS
            sipRes = new  ::wxColour(sipCpp->GetSelectedTextColour(*clr));
            Py_END_ALLOW_THREADS
            sipReleaseType(const_cast< ::wxColour *>(clr),sipType_wxColour,clrState);

            if (PyErr_Occurred())
                return 0;

            return sipConvertFromNewType(sipRes,sipType_wxColour,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_HtmlRenderingStyle, sipName_GetSelectedTextColour, NULL);

    return NULL;
}


PyDoc_STRVAR(doc_wxHtmlRenderingStyle_GetSelectedTextBgColour, "GetSelectedTextBgColour(clr) -> wx.Colour\n"
"\n"
"Returns the colour to use for the selected text's background.");

extern "C" {static PyObject *meth_wxHtmlRenderingStyle_GetSelectedTextBgColour(PyObject *, PyObject *, PyObject *);}
static PyObject *meth_wxHtmlRenderingStyle_GetSelectedTextBgColour(PyObject *sipSelf, PyObject *sipArgs, PyObject *sipKwds)
{
    PyObject *sipParseErr = NULL;
    PyObject *sipOrigSelf = sipSelf;

    {
        const  ::wxColour* clr;
        int clrState = 0;
         ::wxHtmlRenderingStyle *sipCpp;

        static const char *sipKwdList[] = {
            sipName_clr,
        };

        if (sipParseKwdArgs(&sipParseErr, sipArgs, sipKwds, sipKwdList, NULL, "BJ1", &sipSelf, sipType_wxHtmlRenderingStyle, &sipCpp, sipType_wxColour, &clr, &clrState))
        {
             ::wxColour*sipRes;

            if (!sipOrigSelf)
            {
                sipAbstractMethod(sipName_HtmlRenderingStyle, sipName_GetSelectedTextBgColour);
                return NULL;
            }

            PyErr_Clear();

            Py_BEGIN_ALLOW_THREADS
            sipRes = new  ::wxColour(sipCpp->GetSelectedTextBgColour(*clr));
            Py_END_ALLOW_THREADS
            sipReleaseType(const_cast< ::wxColour *>(clr),sipType_wxColour,clrState);

            if (PyErr_Occurred())
                return 0;

            return sipConvertFromNewType(sipRes,sipType_wxColour,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_HtmlRenderingStyle, sipName_GetSelectedTextBgColour, NULL);

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_wxHtmlRenderingStyle(void *, int);}
static void release_wxHtmlRenderingStyle(void *sipCppV, int sipState)
{
    Py_BEGIN_ALLOW_THREADS

    if (sipState & SIP_DERIVED_CLASS)
        delete reinterpret_cast<sipwxHtmlRenderingStyle *>(sipCppV);
    else
        delete reinterpret_cast< ::wxHtmlRenderingStyle *>(sipCppV);

    Py_END_ALLOW_THREADS
}


extern "C" {static void dealloc_wxHtmlRenderingStyle(sipSimpleWrapper *);}
static void dealloc_wxHtmlRenderingStyle(sipSimpleWrapper *sipSelf)
{
    if (sipIsDerivedClass(sipSelf))
        reinterpret_cast<sipwxHtmlRenderingStyle *>(sipGetAddress(sipSelf))->sipPySelf = NULL;

    if (sipIsOwnedByPython(sipSelf))
    {
        release_wxHtmlRenderingStyle(sipGetAddress(sipSelf), sipIsDerivedClass(sipSelf));
    }
}


extern "C" {static void *init_type_wxHtmlRenderingStyle(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_type_wxHtmlRenderingStyle(sipSimpleWrapper *sipSelf, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **, PyObject **sipParseErr)
{
    sipwxHtmlRenderingStyle *sipCpp = 0;

    {
        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, ""))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new sipwxHtmlRenderingStyle();
            Py_END_ALLOW_THREADS

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    {
        const  ::wxHtmlRenderingStyle* a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J9", sipType_wxHtmlRenderingStyle, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new sipwxHtmlRenderingStyle(*a0);
            Py_END_ALLOW_THREADS

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    return NULL;
}


static PyMethodDef methods_wxHtmlRenderingStyle[] = {
    {SIP_MLNAME_CAST(sipName_GetSelectedTextBgColour), (PyCFunction)meth_wxHtmlRenderingStyle_GetSelectedTextBgColour, METH_VARARGS|METH_KEYWORDS, SIP_MLDOC_CAST(doc_wxHtmlRenderingStyle_GetSelectedTextBgColour)},
    {SIP_MLNAME_CAST(sipName_GetSelectedTextColour), (PyCFunction)meth_wxHtmlRenderingStyle_GetSelectedTextColour, METH_VARARGS|METH_KEYWORDS, SIP_MLDOC_CAST(doc_wxHtmlRenderingStyle_GetSelectedTextColour)}
};

PyDoc_STRVAR(doc_wxHtmlRenderingStyle, "wxHtmlSelection is data holder with information about text selection.");


sipClassTypeDef sipTypeDef__html_wxHtmlRenderingStyle = {
    {
        -1,
        0,
        0,
        SIP_TYPE_ABSTRACT|SIP_TYPE_CLASS,
        sipNameNr_wxHtmlRenderingStyle,
        {0},
        0
    },
    {
        sipNameNr_HtmlRenderingStyle,
        {0, 0, 1},
        2, methods_wxHtmlRenderingStyle,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    doc_wxHtmlRenderingStyle,
    -1,
    -1,
    0,
    0,
    init_type_wxHtmlRenderingStyle,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_wxHtmlRenderingStyle,
    0,
    0,
    0,
    release_wxHtmlRenderingStyle,
    0,
    0,
    0,
    0,
    0,
    0,
    0
};
