/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.19.13
 *
 *     Copyright: (c) 2018 by Total Control Software
 *     License:   wxWindows License
 */

#include "sipAPI_core.h"




/* Call the instance's destructor. */
extern "C" {static void release_wxMsgCatalog(void *, int);}
static void release_wxMsgCatalog(void *, int)
{
}


sipClassTypeDef sipTypeDef__core_wxMsgCatalog = {
    {
        -1,
        0,
        0,
        SIP_TYPE_CLASS,
        sipNameNr_wxMsgCatalog,
        {0},
        0
    },
    {
        sipNameNr_MsgCatalog,
        {0, 0, 1},
        0, 0,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    0,
    -1,
    -1,
    0,
    0,
    0,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    0,
    0,
    0,
    0,
    release_wxMsgCatalog,
    0,
    0,
    0,
    0,
    0,
    0,
    0
};
