/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.19.13
 *
 *     Copyright: (c) 2018 by Total Control Software
 *     License:   wxWindows License
 */

#include "sipAPI_core.h"

        #include <wx/event.h>

        #include <wx/event.h>
        #include <wx/object.h>
        #include <wx/object.h>
        #include <wx/object.h>


class sipwxClipboardTextEvent : public  ::wxClipboardTextEvent
{
public:
    sipwxClipboardTextEvent( ::wxEventType,int);
    sipwxClipboardTextEvent(const  ::wxClipboardTextEvent&);
    virtual ~sipwxClipboardTextEvent();

    /*
     * There is a protected method for every virtual method visible from
     * this class.
     */
protected:
     ::wxEventCategory GetEventCategory() const;
     ::wxEvent* Clone() const;

public:
    sipSimpleWrapper *sipPySelf;

private:
    sipwxClipboardTextEvent(const sipwxClipboardTextEvent &);
    sipwxClipboardTextEvent &operator = (const sipwxClipboardTextEvent &);

    char sipPyMethods[2];
};

sipwxClipboardTextEvent::sipwxClipboardTextEvent( ::wxEventType commandType,int id):  ::wxClipboardTextEvent(commandType,id), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipwxClipboardTextEvent::sipwxClipboardTextEvent(const  ::wxClipboardTextEvent& a0):  ::wxClipboardTextEvent(a0), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipwxClipboardTextEvent::~sipwxClipboardTextEvent()
{
    sipInstanceDestroyedEx(&sipPySelf);
}

 ::wxEventCategory sipwxClipboardTextEvent::GetEventCategory() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[0]),sipPySelf,NULL,sipName_GetEventCategory);

    if (!sipMeth)
        return  ::wxClipboardTextEvent::GetEventCategory();

    extern  ::wxEventCategory sipVH__core_96(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *);

    return sipVH__core_96(sipGILState, 0, sipPySelf, sipMeth);
}

 ::wxEvent* sipwxClipboardTextEvent::Clone() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[1]),sipPySelf,NULL,sipName_Clone);

    if (!sipMeth)
        return  ::wxClipboardTextEvent::Clone();

    extern  ::wxEvent* sipVH__core_95(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *);

    return sipVH__core_95(sipGILState, 0, sipPySelf, sipMeth);
}


PyDoc_STRVAR(doc_wxClipboardTextEvent_Clone, "Clone(self) -> Event");

extern "C" {static PyObject *meth_wxClipboardTextEvent_Clone(PyObject *, PyObject *);}
static PyObject *meth_wxClipboardTextEvent_Clone(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerivedClass((sipSimpleWrapper *)sipSelf));

    {
        const  ::wxClipboardTextEvent *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_wxClipboardTextEvent, &sipCpp))
        {
             ::wxEvent*sipRes;

            PyErr_Clear();

            Py_BEGIN_ALLOW_THREADS
            sipRes = (sipSelfWasArg ? sipCpp-> ::wxClipboardTextEvent::Clone() : sipCpp->Clone());
            Py_END_ALLOW_THREADS

            if (PyErr_Occurred())
                return 0;

            return sipConvertFromNewType(sipRes,sipType_wxEvent,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_ClipboardTextEvent, sipName_Clone, doc_wxClipboardTextEvent_Clone);

    return NULL;
}


/* Cast a pointer to a type somewhere in its inheritance hierarchy. */
extern "C" {static void *cast_wxClipboardTextEvent(void *, const sipTypeDef *);}
static void *cast_wxClipboardTextEvent(void *sipCppV, const sipTypeDef *targetType)
{
     ::wxClipboardTextEvent *sipCpp = reinterpret_cast< ::wxClipboardTextEvent *>(sipCppV);

    if (targetType == sipType_wxCommandEvent)
        return static_cast< ::wxCommandEvent *>(sipCpp);

    if (targetType == sipType_wxEvent)
        return static_cast< ::wxEvent *>(sipCpp);

    if (targetType == sipType_wxObject)
        return static_cast< ::wxObject *>(sipCpp);

    return sipCppV;
}


/* Call the instance's destructor. */
extern "C" {static void release_wxClipboardTextEvent(void *, int);}
static void release_wxClipboardTextEvent(void *sipCppV, int sipState)
{
    Py_BEGIN_ALLOW_THREADS

    if (sipState & SIP_DERIVED_CLASS)
        delete reinterpret_cast<sipwxClipboardTextEvent *>(sipCppV);
    else
        delete reinterpret_cast< ::wxClipboardTextEvent *>(sipCppV);

    Py_END_ALLOW_THREADS
}


extern "C" {static void dealloc_wxClipboardTextEvent(sipSimpleWrapper *);}
static void dealloc_wxClipboardTextEvent(sipSimpleWrapper *sipSelf)
{
    if (sipIsDerivedClass(sipSelf))
        reinterpret_cast<sipwxClipboardTextEvent *>(sipGetAddress(sipSelf))->sipPySelf = NULL;

    if (sipIsOwnedByPython(sipSelf))
    {
        release_wxClipboardTextEvent(sipGetAddress(sipSelf), sipIsDerivedClass(sipSelf));
    }
}


extern "C" {static void *init_type_wxClipboardTextEvent(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_type_wxClipboardTextEvent(sipSimpleWrapper *sipSelf, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **, PyObject **sipParseErr)
{
    sipwxClipboardTextEvent *sipCpp = 0;

    {
         ::wxEventType commandType = wxEVT_NULL;
        int id = 0;

        static const char *sipKwdList[] = {
            sipName_commandType,
            sipName_id,
        };

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, sipKwdList, sipUnused, "|ii", &commandType, &id))
        {
            PyErr_Clear();

            Py_BEGIN_ALLOW_THREADS
            sipCpp = new sipwxClipboardTextEvent(commandType,id);
            Py_END_ALLOW_THREADS

            if (PyErr_Occurred())
            {
                delete sipCpp;
                return NULL;
            }

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    {
        const  ::wxClipboardTextEvent* a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J9", sipType_wxClipboardTextEvent, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new sipwxClipboardTextEvent(*a0);
            Py_END_ALLOW_THREADS

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    return NULL;
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_wxClipboardTextEvent[] = {{78, 255, 1}};


static PyMethodDef methods_wxClipboardTextEvent[] = {
    {SIP_MLNAME_CAST(sipName_Clone), meth_wxClipboardTextEvent_Clone, METH_VARARGS, SIP_MLDOC_CAST(doc_wxClipboardTextEvent_Clone)}
};

PyDoc_STRVAR(doc_wxClipboardTextEvent, "ClipboardTextEvent(commandType=wxEVT_NULL, id=0)\n"
"\n"
"This class represents the events generated by a control (typically a\n"
"wxTextCtrl but other windows can generate these events as well) when\n"
"its content gets copied or cut to, or pasted from the clipboard.");


sipClassTypeDef sipTypeDef__core_wxClipboardTextEvent = {
    {
        -1,
        0,
        0,
        SIP_TYPE_SCC|SIP_TYPE_CLASS,
        sipNameNr_wxClipboardTextEvent,
        {0},
        0
    },
    {
        sipNameNr_ClipboardTextEvent,
        {0, 0, 1},
        1, methods_wxClipboardTextEvent,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    doc_wxClipboardTextEvent,
    -1,
    -1,
    supers_wxClipboardTextEvent,
    0,
    init_type_wxClipboardTextEvent,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_wxClipboardTextEvent,
    0,
    0,
    0,
    release_wxClipboardTextEvent,
    cast_wxClipboardTextEvent,
    0,
    0,
    0,
    0,
    0,
    0
};
