/*
 * Module code.
 *
 * Generated by SIP 4.19.13
 *
 *     Copyright: (c) 2018 by Total Control Software
 *     License:   wxWindows License
 */

#include "sipAPI_xml.h"

        #include <wx/object.h>
        #include <wx/xml/xml.h>
        #include <wx/xml/xml.h>
        #include <wx/stream.h>
        #include <wx/stream.h>
        #include <wx/xml/xml.h>

/* Define the strings used by this module. */
const char sipStrings__xml[] = {
    'X', 'M', 'L', 'D', 'O', 'C', '_', 'K', 'E', 'E', 'P', '_', 'W', 'H', 'I', 'T', 'E', 'S', 'P', 'A', 'C', 'E', '_', 'N', 'O', 'D', 'E', 'S', 0,
    'X', 'M', 'L', '_', 'H', 'T', 'M', 'L', '_', 'D', 'O', 'C', 'U', 'M', 'E', 'N', 'T', '_', 'N', 'O', 'D', 'E', 0,
    'X', 'M', 'L', '_', 'D', 'O', 'C', 'U', 'M', 'E', 'N', 'T', '_', 'F', 'R', 'A', 'G', '_', 'N', 'O', 'D', 'E', 0,
    'X', 'M', 'L', '_', 'D', 'O', 'C', 'U', 'M', 'E', 'N', 'T', '_', 'T', 'Y', 'P', 'E', '_', 'N', 'O', 'D', 'E', 0,
    'X', 'M', 'L', '_', 'C', 'D', 'A', 'T', 'A', '_', 'S', 'E', 'C', 'T', 'I', 'O', 'N', '_', 'N', 'O', 'D', 'E', 0,
    'w', 'x', 'X', 'm', 'l', 'D', 'o', 'c', 'u', 'm', 'e', 'n', 't', 'L', 'o', 'a', 'd', 'F', 'l', 'a', 'g', 0,
    'G', 'e', 't', 'L', 'i', 'b', 'r', 'a', 'r', 'y', 'V', 'e', 'r', 's', 'i', 'o', 'n', 'I', 'n', 'f', 'o', 0,
    'X', 'M', 'L', '_', 'E', 'N', 'T', 'I', 'T', 'Y', '_', 'R', 'E', 'F', '_', 'N', 'O', 'D', 'E', 0,
    'D', 'e', 't', 'a', 'c', 'h', 'D', 'o', 'c', 'u', 'm', 'e', 'n', 't', 'N', 'o', 'd', 'e', 0,
    'X', 'M', 'L', '_', 'A', 'T', 'T', 'R', 'I', 'B', 'U', 'T', 'E', '_', 'N', 'O', 'D', 'E', 0,
    'X', 'M', 'L', '_', 'N', 'O', '_', 'I', 'N', 'D', 'E', 'N', 'T', 'A', 'T', 'I', 'O', 'N', 0,
    'X', 'M', 'L', '_', 'N', 'O', 'T', 'A', 'T', 'I', 'O', 'N', '_', 'N', 'O', 'D', 'E', 0,
    'X', 'M', 'L', '_', 'D', 'O', 'C', 'U', 'M', 'E', 'N', 'T', '_', 'N', 'O', 'D', 'E', 0,
    'I', 's', 'W', 'h', 'i', 't', 'e', 's', 'p', 'a', 'c', 'e', 'O', 'n', 'l', 'y', 0,
    'I', 'n', 's', 'e', 'r', 't', 'C', 'h', 'i', 'l', 'd', 'A', 'f', 't', 'e', 'r', 0,
    'X', 'M', 'L', '_', 'C', 'O', 'M', 'M', 'E', 'N', 'T', '_', 'N', 'O', 'D', 'E', 0,
    'X', 'M', 'L', '_', 'E', 'L', 'E', 'M', 'E', 'N', 'T', '_', 'N', 'O', 'D', 'E', 0,
    'i', 'n', 'i', 't', 'i', 'a', 'l', 'S', 'e', 'l', 'e', 'c', 't', 'i', 'o', 'n', 0,
    'n', 'a', 't', 'i', 'v', 'e', 'I', 'n', 'f', 'o', 'S', 't', 'r', 'i', 'n', 'g', 0,
    'S', 'e', 't', 'F', 'i', 'l', 'e', 'E', 'n', 'c', 'o', 'd', 'i', 'n', 'g', 0,
    'S', 'e', 't', 'D', 'o', 'c', 'u', 'm', 'e', 'n', 't', 'N', 'o', 'd', 'e', 0,
    'G', 'e', 't', 'D', 'o', 'c', 'u', 'm', 'e', 'n', 't', 'N', 'o', 'd', 'e', 0,
    'G', 'e', 't', 'F', 'i', 'l', 'e', 'E', 'n', 'c', 'o', 'd', 'i', 'n', 'g', 0,
    'S', 'e', 't', 'N', 'o', 'C', 'o', 'n', 'v', 'e', 'r', 's', 'i', 'o', 'n', 0,
    'G', 'e', 't', 'N', 'o', 'C', 'o', 'n', 'v', 'e', 'r', 's', 'i', 'o', 'n', 0,
    'D', 'e', 'l', 'e', 't', 'e', 'A', 't', 't', 'r', 'i', 'b', 'u', 't', 'e', 0,
    'X', 'M', 'L', '_', 'E', 'N', 'T', 'I', 'T', 'Y', '_', 'N', 'O', 'D', 'E', 0,
    'b', 'a', 'c', 'k', 'g', 'r', 'o', 'u', 'n', 'd', 'B', 'r', 'u', 's', 'h', 0,
    'A', 'p', 'p', 'e', 'n', 'd', 'T', 'o', 'P', 'r', 'o', 'l', 'o', 'g', 0,
    'w', 'x', 'X', 'm', 'l', 'A', 't', 't', 'r', 'i', 'b', 'u', 't', 'e', 0,
    'G', 'e', 't', 'N', 'o', 'd', 'e', 'C', 'o', 'n', 't', 'e', 'n', 't', 0,
    'b', 'o', 'u', 'n', 'd', 'i', 'n', 'g', 'W', 'i', 'n', 'd', 'o', 'w', 0,
    'w', 'x', 'X', 'm', 'l', 'D', 'o', 'c', 'u', 'm', 'e', 'n', 't', 0,
    'p', 'r', 'e', 'c', 'e', 'd', 'i', 'n', 'g', 'N', 'o', 'd', 'e', 0,
    'f', 'o', 'l', 'l', 'o', 'w', 'i', 'n', 'g', 'N', 'o', 'd', 'e', 0,
    'G', 'e', 't', 'L', 'i', 'n', 'e', 'N', 'u', 'm', 'b', 'e', 'r', 0,
    'G', 'e', 't', 'A', 't', 't', 'r', 'i', 'b', 'u', 't', 'e', 's', 0,
    'X', 'M', 'L', '_', 'T', 'E', 'X', 'T', '_', 'N', 'O', 'D', 'E', 0,
    'w', 'x', 'X', 'm', 'l', 'N', 'o', 'd', 'e', 'T', 'y', 'p', 'e', 0,
    'i', 'n', 'i', 't', 'i', 'a', 'l', 'C', 'o', 'l', 'o', 'u', 'r', 0,
    'm', 's', 'g', 'I', 'd', 'L', 'a', 'n', 'g', 'u', 'a', 'g', 'e', 0,
    'n', 'o', 'c', 'o', 'n', 'v', 'e', 'r', 's', 'i', 'o', 'n', 0,
    'H', 'a', 's', 'A', 't', 't', 'r', 'i', 'b', 'u', 't', 'e', 0,
    'G', 'e', 't', 'A', 't', 't', 'r', 'i', 'b', 'u', 't', 'e', 0,
    'A', 'd', 'd', 'A', 't', 't', 'r', 'i', 'b', 'u', 't', 'e', 0,
    's', 'i', 'z', 'e', 'I', 'n', 'P', 'i', 'x', 'e', 'l', 's', 0,
    'c', 'i', 'r', 'c', 'l', 'e', 'C', 'e', 'n', 't', 'e', 'r', 0,
    'm', 's', 'g', 'I', 'd', 'C', 'h', 'a', 'r', 's', 'e', 't', 0,
    'b', 'L', 'o', 'a', 'd', 'D', 'e', 'f', 'a', 'u', 'l', 't', 0,
    'I', 'n', 's', 'e', 'r', 't', 'C', 'h', 'i', 'l', 'd', 0,
    'g', 'r', 'a', 'n', 'd', 'p', 'a', 'r', 'e', 'n', 't', 0,
    'X', 'M', 'L', 'D', 'O', 'C', '_', 'N', 'O', 'N', 'E', 0,
    'X', 'M', 'L', '_', 'P', 'I', '_', 'N', 'O', 'D', 'E', 0,
    'b', 'm', 'p', 'D', 'i', 's', 'a', 'b', 'l', 'e', 'd', 0,
    'R', 'e', 'm', 'o', 'v', 'e', 'C', 'h', 'i', 'l', 'd', 0,
    'e', 'x', 'c', 'l', 'u', 'd', 'e', 'I', 't', 'e', 'm', 0,
    'G', 'e', 't', 'C', 'h', 'i', 'l', 'd', 'r', 'e', 'n', 0,
    'a', 'u', 't', 'o', 'P', 'a', 'i', 'n', 't', 'D', 'C', 0,
    't', 'r', 'a', 'n', 's', 'C', 'o', 'l', 'o', 'u', 'r', 0,
    'o', 'r', 'i', 'g', 'S', 't', 'r', 'i', 'n', 'g', '2', 0,
    'S', 'e', 't', 'V', 'e', 'r', 's', 'i', 'o', 'n', 0,
    'i', 'n', 'd', 'e', 'n', 't', 's', 't', 'e', 'p', 0,
    'D', 'e', 't', 'a', 'c', 'h', 'R', 'o', 'o', 't', 0,
    'S', 'e', 't', 'C', 'o', 'n', 't', 'e', 'n', 't', 0,
    'G', 'e', 't', 'C', 'o', 'n', 't', 'e', 'n', 't', 0,
    'i', 'm', 'a', 'g', 'e', 'I', 'n', 'd', 'e', 'x', 0,
    'w', 'i', 'd', 't', 'h', 'T', 'i', 't', 'l', 'e', 0,
    'c', 'l', 'i', 'e', 'n', 't', 'D', 'a', 't', 'a', 0,
    'h', 'e', 'l', 'p', 'S', 't', 'r', 'i', 'n', 'g', 0,
    'p', 'r', 'o', 'p', 'o', 'r', 't', 'i', 'o', 'n', 0,
    'd', 'e', 'f', 'a', 'u', 'l', 't', 'V', 'a', 'l', 0,
    'G', 'e', 't', 'V', 'e', 'r', 's', 'i', 'o', 'n', 0,
    'm', 'a', 's', 'k', 'C', 'o', 'l', 'o', 'u', 'r', 0,
    's', 't', 'a', 'r', 't', 'A', 'n', 'g', 'l', 'e', 0,
    'm', 'e', 't', 'a', 'F', 'i', 'l', 'e', 'D', 'C', 0,
    'd', 'e', 's', 't', 'C', 'o', 'l', 'o', 'u', 'r', 0,
    'i', 'n', 'd', 'e', 'x', 'A', 'c', 'c', 'e', 'l', 0,
    'n', 'a', 't', 'i', 'v', 'e', 'I', 'n', 'f', 'o', 0,
    'n', 'e', 'w', '_', 'h', 'e', 'i', 'g', 'h', 't', 0,
    'b', 'i', 'n', 'a', 'r', 'y', 'd', 'a', 't', 'a', 0,
    's', 't', 'r', 'e', 'a', 'm', '_', 'o', 'u', 't', 0,
    'b', 'r', 'i', 'g', 'h', 't', 'n', 'e', 's', 's', 0,
    'o', 'r', 'i', 'g', 'S', 't', 'r', 'i', 'n', 'g', 0,
    'w', 'x', 'X', 'm', 'l', 'N', 'o', 'd', 'e', 0,
    's', 'e', 'c', 't', 'i', 'o', 'n', 'N', 'o', 0,
    's', 'h', 'o', 'r', 't', 'H', 'e', 'l', 'p', 0,
    'c', 'o', 'm', 'p', 'l', 'e', 't', 'e', 'r', 0,
    'c', 'o', 'l', 'u', 'm', 'n', 'M', 'a', 'x', 0,
    'c', 'o', 'l', 'u', 'm', 'n', 'M', 'i', 'n', 0,
    'S', 'e', 't', 'P', 'a', 'r', 'e', 'n', 't', 0,
    's', 'i', 'z', 'e', 'F', 'l', 'a', 'g', 's', 0,
    'r', 'e', 'c', 'u', 'r', 's', 'i', 'v', 'e', 0,
    'G', 'e', 't', 'P', 'a', 'r', 'e', 'n', 't', 0,
    'p', 'r', 'i', 'n', 't', 'e', 'r', 'D', 'C', 0,
    'a', 'l', 'i', 'g', 'n', 'm', 'e', 'n', 't', 0,
    'f', 'i', 'l', 'l', 'S', 't', 'y', 'l', 'e', 0,
    't', 'o', 'l', 'e', 'r', 'a', 'n', 'c', 'e', 0,
    'f', 'a', 'c', 'e', 'n', 'a', 'm', 'e', 's', 0,
    'u', 'n', 'd', 'e', 'r', 'l', 'i', 'n', 'e', 0,
    'p', 'i', 'x', 'e', 'l', 'S', 'i', 'z', 'e', 0,
    'p', 'o', 'i', 'n', 't', 'S', 'i', 'z', 'e', 0,
    'i', 'm', 'a', 'g', 'e', 'T', 'y', 'p', 'e', 0,
    'e', 'x', 't', 'e', 'n', 's', 'i', 'o', 'n', 0,
    'n', 'e', 'w', '_', 'w', 'i', 'd', 't', 'h', 0,
    't', 'h', 'r', 'e', 's', 'h', 'o', 'l', 'd', 0,
    'c', 'l', 'o', 'c', 'k', 'w', 'i', 's', 'e', 0,
    's', 't', 'r', 'e', 'a', 'm', '_', 'i', 'n', 0,
    'd', 'i', 'r', 'e', 'c', 't', 'i', 'o', 'n', 0,
    's', 'h', 'o', 'r', 't', 'N', 'a', 'm', 'e', 0,
    'a', 't', 't', 'r', 'N', 'a', 'm', 'e', 0,
    's', 'e', 'l', 'I', 'm', 'a', 'g', 'e', 0,
    'l', 'o', 'n', 'g', 'H', 'e', 'l', 'p', 0,
    'm', 'e', 'n', 'u', 'I', 't', 'e', 'm', 0,
    'A', 'd', 'd', 'C', 'h', 'i', 'l', 'd', 0,
    'u', 's', 'e', 'r', 'D', 'a', 't', 'a', 0,
    'S', 'e', 't', 'V', 'a', 'l', 'u', 'e', 0,
    'e', 'n', 'd', 'A', 'n', 'g', 'l', 'e', 0,
    'm', 'e', 'm', 'o', 'r', 'y', 'D', 'C', 0,
    'w', 'i', 'n', 'd', 'o', 'w', 'D', 'C', 0,
    'f', 'a', 'c', 'e', 'n', 'a', 'm', 'e', 0,
    'e', 'n', 'c', 'o', 'd', 'i', 'n', 'g', 0,
    'f', 'a', 'c', 'e', 'N', 'a', 'm', 'e', 0,
    't', 'e', 'x', 't', 'd', 'a', 't', 'a', 0,
    'm', 'i', 'm', 'e', 't', 'y', 'p', 'e', 0,
    'l', 'o', 'c', 'a', 't', 'i', 'o', 'n', 0,
    'w', 'e', 'i', 'g', 'h', 't', '_', 'b', 0,
    'w', 'e', 'i', 'g', 'h', 't', '_', 'g', 0,
    'w', 'e', 'i', 'g', 'h', 't', '_', 'r', 0,
    'f', 'i', 'l', 'e', 'n', 'a', 'm', 'e', 0,
    'G', 'e', 't', 'D', 'e', 'p', 't', 'h', 0,
    'G', 'e', 't', 'V', 'a', 'l', 'u', 'e', 0,
    'S', 'e', 't', 'R', 'o', 'o', 't', 0,
    'G', 'e', 't', 'R', 'o', 'o', 't', 0,
    'S', 'e', 't', 'N', 'e', 'x', 't', 0,
    'c', 'o', 'n', 't', 'e', 'n', 't', 0,
    'h', 'o', 't', 's', 'p', 'o', 't', 0,
    'c', 'a', 'p', 't', 'i', 'o', 'n', 0,
    'c', 'o', 'l', 'n', 'a', 'm', 'e', 0,
    'h', 'e', 'a', 'd', 'i', 'n', 'g', 0,
    'c', 'o', 'n', 't', 'r', 'o', 'l', 0,
    'G', 'e', 't', 'N', 'e', 'x', 't', 0,
    'i', 'm', 'a', 'g', 'e', 'I', 'd', 0,
    'c', 'h', 'o', 'i', 'c', 'e', 's', 0,
    'u', 'n', 'i', 't', 'M', 'a', 'x', 0,
    'u', 'n', 'i', 't', 'M', 'i', 'n', 0,
    's', 'u', 'b', 'm', 'e', 'n', 'u', 0,
    's', 'u', 'b', 'M', 'e', 'n', 'u', 0,
    'v', 'a', 'r', 'i', 'a', 'n', 't', 0,
    'i', 'n', 'c', 'S', 'i', 'z', 'e', 0,
    'm', 'a', 'x', 'S', 'i', 'z', 'e', 0,
    'm', 'i', 'n', 'S', 'i', 'z', 'e', 0,
    'n', 'e', 'w', 'i', 't', 'e', 'm', 0,
    'o', 'v', 'e', 'r', 'l', 'a', 'y', 0,
    'm', 'e', 's', 's', 'a', 'g', 'e', 0,
    'u', 's', 'e', 'M', 'a', 's', 'k', 0,
    'p', 't', 'S', 't', 'a', 'r', 't', 0,
    'S', 'e', 't', 'N', 'a', 'm', 'e', 0,
    'S', 'e', 't', 'T', 'y', 'p', 'e', 0,
    'G', 'e', 't', 'T', 'y', 'p', 'e', 0,
    'G', 'e', 't', 'N', 'a', 'm', 'e', 0,
    'w', 'e', 'e', 'k', 'd', 'a', 'y', 0,
    'w', 'x', '.', '_', 'x', 'm', 'l', 0,
    'c', 'l', 'i', 'e', 'n', 't', 0,
    's', 'e', 'r', 'v', 'e', 'r', 0,
    'd', 'i', 'a', 'l', 'o', 'g', 0,
    't', 'o', 'o', 'l', 'I', 'd', 0,
    'l', 'i', 'n', 'e', 'N', 'o', 0,
    'r', 'o', 'w', 'M', 'a', 'x', 0,
    'r', 'o', 'w', 'M', 'i', 'n', 0,
    'b', 'o', 'r', 'd', 'e', 'r', 0,
    'e', 'n', 'a', 'b', 'l', 'e', 0,
    'w', 'i', 'n', 'd', 'o', 'w', 0,
    'r', 'a', 'd', 'i', 'u', 's', 0,
    'c', 'e', 'n', 't', 'r', 'e', 0,
    'r', 'e', 'g', 'i', 'o', 'n', 0,
    'w', 'e', 'i', 'g', 'h', 't', 0,
    'f', 'a', 'm', 'i', 'l', 'y', 0,
    'b', 'i', 't', 'm', 'a', 'p', 0,
    's', 't', 'r', 'e', 'a', 'm', 0,
    'b', 'u', 'f', 'f', 'e', 'r', 0,
    'i', 'a', 'l', 'p', 'h', 'a', 0,
    'c', 'o', 'l', 'u', 'm', 'n', 0,
    'c', 'o', 'l', 'o', 'u', 'r', 0,
    'b', 'o', 't', 't', 'o', 'm', 0,
    'p', 'l', 'u', 'r', 'a', 'l', 0,
    's', 't', 'r', 'i', 'n', 'g', 0,
    'd', 'o', 'm', 'a', 'i', 'n', 0,
    'l', 'o', 'c', 'a', 'l', 'e', 0,
    'f', 'o', 'r', 'm', 'a', 't', 0,
    'a', 't', 't', 'r', 's', 0,
    'p', 'o', 'p', 'u', 'p', 0,
    'i', 't', 'e', 'm', 's', 0,
    't', 's', 'i', 'z', 'e', 0,
    'l', 'a', 'b', 'e', 'l', 0,
    'n', 'e', 'w', 's', 'z', 0,
    'o', 'l', 'd', 's', 'z', 0,
    'r', 'a', 't', 'i', 'o', 0,
    's', 'i', 'z', 'e', 'r', 0,
    'e', 'v', 'e', 'n', 't', 0,
    'l', 'e', 'v', 'e', 'l', 0,
    'c', 'h', 'i', 'l', 'd', 0,
    's', 't', 'o', 'p', 's', 0,
    'p', 'o', 'i', 'n', 't', 0,
    's', 't', 'a', 'r', 't', 0,
    'p', 't', 'E', 'n', 'd', 0,
    'b', 'r', 'u', 's', 'h', 0,
    's', 't', 'y', 'l', 'e', 0,
    'a', 'n', 'g', 'l', 'e', 0,
    'c', 'l', 'e', 'a', 'r', 0,
    'i', 'm', 'a', 'g', 'e', 0,
    'g', 'r', 'e', 'e', 'n', 0,
    'd', 'e', 'n', 'u', 'm', 0,
    'r', 'i', 'g', 'h', 't', 0,
    'i', 'n', 'd', 'e', 'x', 0,
    'd', 'e', 'p', 't', 'h', 0,
    'c', 'o', 'u', 'n', 't', 0,
    'f', 'l', 'a', 'g', 's', 0,
    'm', 'o', 'n', 't', 'h', 0,
    'v', 'a', 'l', 'u', 'e', 0,
    'n', 'o', 'd', 'e', 0,
    'n', 'e', 'x', 't', 0,
    't', 'o', 'o', 'l', 0,
    'a', 't', 't', 'r', 0,
    'f', 'r', 'o', 'm', 0,
    'u', 'n', 'i', 't', 0,
    'h', 'e', 'l', 'p', 0,
    'k', 'i', 'n', 'd', 0,
    'i', 'n', 'c', 'H', 0,
    'i', 'n', 'c', 'W', 0,
    'm', 'a', 'x', 'H', 0,
    'm', 'a', 'x', 'W', 0,
    'm', 'i', 'n', 'H', 0,
    'm', 'i', 'n', 'W', 0,
    's', 'p', 'a', 'n', 0,
    'S', 'a', 'v', 'e', 0,
    's', 'h', 'o', 'w', 0,
    'L', 'o', 'a', 'd', 0,
    't', 'e', 'x', 't', 0,
    'b', 'a', 's', 'e', 0,
    'f', 'o', 'n', 't', 0,
    'i', 'c', 'o', 'n', 0,
    'f', 'i', 'l', 'e', 0,
    'p', 'a', 't', 'h', 0,
    'b', 'l', 'u', 'e', 0,
    'd', 'e', 's', 't', 0,
    's', 'r', 'c', '2', 0,
    's', 'r', 'c', '1', 0,
    'l', 'e', 'f', 't', 0,
    'r', 'e', 'c', 't', 0,
    'f', 'l', 'a', 'g', 0,
    'l', 'a', 'n', 'g', 0,
    'I', 's', 'O', 'k', 0,
    't', 'i', 'm', 'e', 0,
    'd', 'i', 'f', 'f', 0,
    'd', 'a', 't', 'e', 0,
    'y', 'e', 'a', 'r', 0,
    'i', 'n', 'f', 'o', 0,
    'd', 'o', 'c', 0,
    'i', 'd', 'x', 0,
    't', 'i', 'p', 0,
    'l', 'e', 'n', 0,
    'b', 'u', 'f', 0,
    'm', 's', 'g', 0,
    'p', 't', '2', 0,
    'p', 't', '1', 0,
    'p', 'e', 'n', 0,
    'b', 'm', 'p', 0,
    'R', 'G', 'B', 0,
    'r', 'e', 'd', 0,
    'c', 'o', 'l', 0,
    'r', 'o', 'w', 0,
    't', 'o', 'p', 0,
    'p', 'o', 's', 0,
    's', 't', 'r', 0,
    't', 'o', 0,
    'y', 'o', 0,
    'x', 'o', 0,
    'd', 'c', 0,
    'y', '3', 0,
    'x', '3', 0,
    'y', '2', 0,
    'x', '2', 0,
    'y', '1', 0,
    'x', '1', 0,
    'e', 'a', 0,
    's', 'a', 0,
    'y', 'c', 0,
    'x', 'c', 0,
    'm', 'b', 0,
    'm', 'g', 0,
    'm', 'r', 0,
    'd', 'y', 0,
    'p', 't', 0,
    'i', 'd', 0,
    'd', 't', 0,
};

bool sipVH__xml_9(sip_gilstate_t sipGILState, sipVirtErrorHandlerFunc sipErrorHandler, sipSimpleWrapper *sipPySelf, PyObject *sipMethod,  ::wxOutputStream& stream,int indentstep)
{
    bool sipRes = 0;
    PyObject *sipResObj = sipCallMethod(0, sipMethod, "Di", &stream, sipType_wxOutputStream, NULL, indentstep);

    sipParseResultEx(sipGILState, sipErrorHandler, sipPySelf, sipMethod, sipResObj, "b", &sipRes);

    return sipRes;
}

bool sipVH__xml_8(sip_gilstate_t sipGILState, sipVirtErrorHandlerFunc sipErrorHandler, sipSimpleWrapper *sipPySelf, PyObject *sipMethod, const  ::wxString& filename,int indentstep)
{
    bool sipRes = 0;
    PyObject *sipResObj = sipCallMethod(0, sipMethod, "Ni", new  ::wxString(filename), sipType_wxString, NULL, indentstep);

    sipParseResultEx(sipGILState, sipErrorHandler, sipPySelf, sipMethod, sipResObj, "b", &sipRes);

    return sipRes;
}

bool sipVH__xml_7(sip_gilstate_t sipGILState, sipVirtErrorHandlerFunc sipErrorHandler, sipSimpleWrapper *sipPySelf, PyObject *sipMethod,  ::wxInputStream& stream,const  ::wxString& encoding,int flags)
{
    bool sipRes = 0;
    PyObject *sipResObj = sipCallMethod(0, sipMethod, "DNi", &stream, sipType_wxInputStream, NULL, new  ::wxString(encoding), sipType_wxString, NULL, flags);

    sipParseResultEx(sipGILState, sipErrorHandler, sipPySelf, sipMethod, sipResObj, "b", &sipRes);

    return sipRes;
}

bool sipVH__xml_6(sip_gilstate_t sipGILState, sipVirtErrorHandlerFunc sipErrorHandler, sipSimpleWrapper *sipPySelf, PyObject *sipMethod, const  ::wxString& filename,const  ::wxString& encoding,int flags)
{
    bool sipRes = 0;
    PyObject *sipResObj = sipCallMethod(0, sipMethod, "NNi", new  ::wxString(filename), sipType_wxString, NULL, new  ::wxString(encoding), sipType_wxString, NULL, flags);

    sipParseResultEx(sipGILState, sipErrorHandler, sipPySelf, sipMethod, sipResObj, "b", &sipRes);

    return sipRes;
}

bool sipVH__xml_5(sip_gilstate_t sipGILState, sipVirtErrorHandlerFunc sipErrorHandler, sipSimpleWrapper *sipPySelf, PyObject *sipMethod,  ::wxXmlNode*child)
{
    bool sipRes = 0;
    PyObject *sipResObj = sipCallMethod(0, sipMethod, "D", child, sipType_wxXmlNode, NULL);

    sipParseResultEx(sipGILState, sipErrorHandler, sipPySelf, sipMethod, sipResObj, "b", &sipRes);

    return sipRes;
}

bool sipVH__xml_4(sip_gilstate_t sipGILState, sipVirtErrorHandlerFunc sipErrorHandler, sipSimpleWrapper *sipPySelf, PyObject *sipMethod,  ::wxXmlNode*child, ::wxXmlNode*followingNode)
{
    bool sipRes = 0;
    PyObject *sipResObj = sipCallMethod(0, sipMethod, "DD", child, sipType_wxXmlNode, NULL, followingNode, sipType_wxXmlNode, NULL);

    sipParseResultEx(sipGILState, sipErrorHandler, sipPySelf, sipMethod, sipResObj, "b", &sipRes);

    return sipRes;
}

bool sipVH__xml_3(sip_gilstate_t sipGILState, sipVirtErrorHandlerFunc sipErrorHandler, sipSimpleWrapper *sipPySelf, PyObject *sipMethod, const  ::wxString& name)
{
    bool sipRes = 0;
    PyObject *sipResObj = sipCallMethod(0, sipMethod, "N", new  ::wxString(name), sipType_wxString, NULL);

    sipParseResultEx(sipGILState, sipErrorHandler, sipPySelf, sipMethod, sipResObj, "b", &sipRes);

    return sipRes;
}

void sipVH__xml_2(sip_gilstate_t sipGILState, sipVirtErrorHandlerFunc sipErrorHandler, sipSimpleWrapper *sipPySelf, PyObject *sipMethod,  ::wxXmlNode*child)
{
    sipCallProcedureMethod(sipGILState, sipErrorHandler, sipPySelf, sipMethod, "D", child, sipType_wxXmlNode, NULL);
}

void sipVH__xml_1(sip_gilstate_t sipGILState, sipVirtErrorHandlerFunc sipErrorHandler, sipSimpleWrapper *sipPySelf, PyObject *sipMethod,  ::wxXmlAttribute*attr)
{
    sipCallProcedureMethod(sipGILState, sipErrorHandler, sipPySelf, sipMethod, "D", attr, sipType_wxXmlAttribute, NULL);
}

void sipVH__xml_0(sip_gilstate_t sipGILState, sipVirtErrorHandlerFunc sipErrorHandler, sipSimpleWrapper *sipPySelf, PyObject *sipMethod, const  ::wxString& name,const  ::wxString& value)
{
    sipCallProcedureMethod(sipGILState, sipErrorHandler, sipPySelf, sipMethod, "NN", new  ::wxString(name), sipType_wxString, NULL, new  ::wxString(value), sipType_wxString, NULL);
}
static sipEnumTypeDef enumTypes[] = {
    {{-1, 0, 0, SIP_TYPE_ENUM, sipNameNr_wxXmlDocumentLoadFlag, {0}, 0}, sipNameNr_XmlDocumentLoadFlag, -1, NULL},
    {{-1, 0, 0, SIP_TYPE_ENUM, sipNameNr_wxXmlNodeType, {0}, 0}, sipNameNr_XmlNodeType, -1, NULL},
};

/* These are the enum members of all global enums. */
static sipEnumMemberDef enummembers[] = {
    {sipName_XMLDOC_KEEP_WHITESPACE_NODES, static_cast<int>(::wxXMLDOC_KEEP_WHITESPACE_NODES), 2},
    {sipName_XMLDOC_NONE, static_cast<int>(::wxXMLDOC_NONE), 2},
    {sipName_XML_ATTRIBUTE_NODE, static_cast<int>(::wxXML_ATTRIBUTE_NODE), 4},
    {sipName_XML_CDATA_SECTION_NODE, static_cast<int>(::wxXML_CDATA_SECTION_NODE), 4},
    {sipName_XML_COMMENT_NODE, static_cast<int>(::wxXML_COMMENT_NODE), 4},
    {sipName_XML_DOCUMENT_FRAG_NODE, static_cast<int>(::wxXML_DOCUMENT_FRAG_NODE), 4},
    {sipName_XML_DOCUMENT_NODE, static_cast<int>(::wxXML_DOCUMENT_NODE), 4},
    {sipName_XML_DOCUMENT_TYPE_NODE, static_cast<int>(::wxXML_DOCUMENT_TYPE_NODE), 4},
    {sipName_XML_ELEMENT_NODE, static_cast<int>(::wxXML_ELEMENT_NODE), 4},
    {sipName_XML_ENTITY_NODE, static_cast<int>(::wxXML_ENTITY_NODE), 4},
    {sipName_XML_ENTITY_REF_NODE, static_cast<int>(::wxXML_ENTITY_REF_NODE), 4},
    {sipName_XML_HTML_DOCUMENT_NODE, static_cast<int>(::wxXML_HTML_DOCUMENT_NODE), 4},
    {sipName_XML_NOTATION_NODE, static_cast<int>(::wxXML_NOTATION_NODE), 4},
    {sipName_XML_PI_NODE, static_cast<int>(::wxXML_PI_NODE), 4},
    {sipName_XML_TEXT_NODE, static_cast<int>(::wxXML_TEXT_NODE), 4},
};


/*
 * This defines each type in this module.
 */
sipTypeDef *sipExportedTypes__xml[] = {
    &sipTypeDef__xml_wxXmlAttribute.ctd_base,
    &sipTypeDef__xml_wxXmlDocument.ctd_base,
    &enumTypes[0].etd_base,
    &sipTypeDef__xml_wxXmlNode.ctd_base,
    &enumTypes[1].etd_base,
};


/* This defines the types that this module needs to import from _core. */
sipImportedTypeDef sipImportedTypes__xml__core[] = {
    {"wxInputStream"},
    {"wxObject"},
    {"wxOutputStream"},
    {"wxString"},
    {"wxVersionInfo"},
    {NULL}
};


/* This defines the modules that this module needs to import. */
static sipImportedModuleDef importsTable[] = {
    {"wx._core", sipImportedTypes__xml__core, NULL, NULL},
    {NULL, NULL, NULL, NULL}
};


/* Define the ints to be added to this module dictionary. */
static sipIntInstanceDef intInstances[] = {
    {sipName_XML_NO_INDENTATION, wxXML_NO_INDENTATION},
    {0, 0}
};


/* This defines this module. */
sipExportedModuleDef sipModuleAPI__xml = {
    0,
    SIP_API_MINOR_NR,
    sipNameNr_wx__xml,
    0,
    sipStrings__xml,
    importsTable,
    NULL,
    5,
    sipExportedTypes__xml,
    NULL,
    15,
    enummembers,
    0,
    NULL,
    NULL,
    NULL,
    {NULL, NULL, NULL, NULL, intInstances, NULL, NULL, NULL, NULL, NULL},
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
};


/* The SIP API and the APIs of any imported modules. */
const sipAPIDef *sipAPI__xml;


/* The Python module initialisation function. */
#if PY_MAJOR_VERSION >= 3
#define SIP_MODULE_ENTRY        PyInit__xml
#define SIP_MODULE_TYPE         PyObject *
#define SIP_MODULE_DISCARD(r)   Py_DECREF(r)
#define SIP_MODULE_RETURN(r)    return (r)
#else
#define SIP_MODULE_ENTRY        init_xml
#define SIP_MODULE_TYPE         void
#define SIP_MODULE_DISCARD(r)
#define SIP_MODULE_RETURN(r)    return
#endif

#if defined(SIP_STATIC_MODULE)
extern "C" SIP_MODULE_TYPE SIP_MODULE_ENTRY()
#else
PyMODINIT_FUNC SIP_MODULE_ENTRY()
#endif
{
    static PyMethodDef sip_methods[] = {
        {0, 0, 0, 0}
    };

#if PY_MAJOR_VERSION >= 3
    static PyModuleDef sip_module_def = {
        PyModuleDef_HEAD_INIT,
        "wx._xml",
        NULL,
        -1,
        sip_methods,
        NULL,
        NULL,
        NULL,
        NULL
    };
#endif

    PyObject *sipModule, *sipModuleDict;
    PyObject *sip_sipmod, *sip_capiobj;

    /* Initialise the module and get it's dictionary. */
#if PY_MAJOR_VERSION >= 3
    sipModule = PyModule_Create(&sip_module_def);
#elif PY_VERSION_HEX >= 0x02050000
    sipModule = Py_InitModule(sipName_wx__xml, sip_methods);
#else
    sipModule = Py_InitModule(const_cast<char *>(sipName_wx__xml), sip_methods);
#endif

    if (sipModule == NULL)
        SIP_MODULE_RETURN(NULL);

    sipModuleDict = PyModule_GetDict(sipModule);

    /* Get the SIP module's API. */
#if PY_VERSION_HEX >= 0x02050000
    sip_sipmod = PyImport_ImportModule("wx.siplib");
#else
    sip_sipmod = PyImport_ImportModule(const_cast<char *>("wx.siplib"));
#endif

    if (sip_sipmod == NULL)
    {
        SIP_MODULE_DISCARD(sipModule);
        SIP_MODULE_RETURN(NULL);
    }

    sip_capiobj = PyDict_GetItemString(PyModule_GetDict(sip_sipmod), "_C_API");
    Py_DECREF(sip_sipmod);

#if defined(SIP_USE_PYCAPSULE)
    if (sip_capiobj == NULL || !PyCapsule_CheckExact(sip_capiobj))
#else
    if (sip_capiobj == NULL || !PyCObject_Check(sip_capiobj))
#endif
    {
        SIP_MODULE_DISCARD(sipModule);
        SIP_MODULE_RETURN(NULL);
    }

#if defined(SIP_USE_PYCAPSULE)
    sipAPI__xml = reinterpret_cast<const sipAPIDef *>(PyCapsule_GetPointer(sip_capiobj, "wx.siplib._C_API"));
#else
    sipAPI__xml = reinterpret_cast<const sipAPIDef *>(PyCObject_AsVoidPtr(sip_capiobj));
#endif

#if defined(SIP_USE_PYCAPSULE)
    if (sipAPI__xml == NULL)
    {
        SIP_MODULE_DISCARD(sipModule);
        SIP_MODULE_RETURN(NULL);
    }
#endif

    /* Export the module and publish it's API. */
    if (sipExportModule(&sipModuleAPI__xml,SIP_API_MAJOR_NR,SIP_API_MINOR_NR,0) < 0)
    {
        SIP_MODULE_DISCARD(sipModule);
        SIP_MODULE_RETURN(0);
    }
    /* Initialise the module now all its dependencies have been set up. */
    if (sipInitModule(&sipModuleAPI__xml,sipModuleDict) < 0)
    {
        SIP_MODULE_DISCARD(sipModule);
        SIP_MODULE_RETURN(0);
    }

    SIP_MODULE_RETURN(sipModule);
}
