
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-01-11T20:24:38+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c56ac9c2e1a3efc5610926d8fed4628718317854",
 "version": "v0.6.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
