[tool.poetry]
name = "dikicli"
version = "0.3.2"
description = "Commandline interface to diki.pl polish-english dictionary."
authors = ["Dawid Zych <dawid.zych@yandex.com>"]
license = "MIT"
readme = "README.md"
repository = 'https://github.com/silenc3r/dikicli'
homepage = 'https://github.com/silenc3r/dikicli'

[tool.poetry.dependencies]
python = "^3.4"
beautifulsoup4 = "*"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-vcr = "*"
pylint = "*"
isort = "^4.3"

[tool.poetry.scripts]
diki = "dikicli.cli:main"

[tool.isort]
force_single_line = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
