dist: xenial
sudo: false
language: python

python:
- 3.6
- &latest_py3 3.7

jobs:
  fast_finish: true
  include:
  - stage: deploy
    if: tag IS present
    python: *latest_py3
    before_script: skip
    env:
    - TWINE_USERNAME=jaraco
    # TWINE_PASSWORD
    - secure: OEcclXivDJUwdHk3JGthKIOU1S9LuTBL4c+SFXERyx2ELmuIKBooVMe1O5gvrzLibokdh8VNiEfs1bbCa8W+8h00IeYW74FnnggT9sQmGJo3vraIiC8AXy0VkMTWdNGdbXk+lfrEVskU2ZM83TEdKAu06mVv1i5Y7xJHVHbqUAHsliSTnbclZgjfInASLrTCzUwl9J9LW2zkwT9DMCg3Oi8hVKxHMXrA8CEVAN813Ul4zLR+pcly50l2a4DpFxPmEvZO9X+kMzC4tuU2tg8efv/1GOlPUl5spFThtrFgeKTRUwu4UJIukxrAsXxnQkY+7gO7qI9M3W26B1IgjkaHcfsruY2wuHXrGEpgGx8tWkPacLuF4K3lU96seaFi9jdUz/1266M3aY5b75rlZhcC39B6n+YvMqhuXDySlIG2ZraY07umUEThnuppJfE20pSGN96YS+DyUPLRTRe2q5NuoYTlQ3qwlmGtJ/tE6n0GLA3eLQluSbBXrjqWjnEYgIODSKwpZyaO+7Rrpzx55652uIeZE4bNpUBQfpOkjSxS98vQNVs3Unc0px7tuYnh4hpdmwGCG+/zxky7AWEzyB9tpqNy75sQy4hbANLA2VEuuVHq7hJcmzODU0neK3D4Snk47hyopxDG2eO4Frsf8s+SQ0S76+hwApxJjgf59uEDNN4=
    - TOX_TESTENV_PASSENV="TWINE_USERNAME TWINE_PASSWORD"
    script: tox -e release

cache: pip

install:
- pip install tox tox-venv

before_script:
  # Disable IPv6. Ref travis-ci/travis-ci#8361
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
    fi
script: tox
