# This is a common .travis.yml for generating library release zip files for
# CircuitPython library releases using circuitpython-build-tools.
# See https://github.com/adafruit/circuitpython-build-tools for detailed setup
# instructions.

dist: trusty
sudo: false
language: python
python:
- '3.6'
cache:
  pip: true
deploy:
  - provider: releases
    api_key: "$GITHUB_TOKEN"
    file_glob: true
    file: "$TRAVIS_BUILD_DIR/bundles/*"
    skip_cleanup: true
    overwrite: true
    on:
      tags: true
  - provider: pypi
    user: adafruit-travis
    on:
      tags: true
    password:
      secure: 3in/QXIrXq6l2QJRYjUnufB6rYnZVptU9VeKsWsLSLty3BYnxbN8PEXWDu1h0q7W1s/aHcMrB25yZTRXnwAvYxrOsmA6ZYmmIX2CcT/bKbNWE+kKwl90BA48Ip8Awxc/jZOJ/gDCtbqE9mf8AFVd5zXzJUbgE8p6FSCurJLkJevBkWUcLws1KKEN0+kMu5+z8Ghi/HPacQ0Uvr2fNvSbGI0/hmPlJfZuhdp1zdo3R5cS2E4IiIO6UPDUINVMzQOBKcngZ14NIGUjSqaff1aP4elxY7qAndl3qMgoLq0EfVpxy2trsTvtSkpTqfSZamMZiZWF0T/oD7RkOllf2j3F6b37ZTZWhldZuLzDApLFy1aVVEme+yoPnWNPbYaREUkyhSmeA2bOAsoN7Mn5NG9HZOujrS/m5sJi8PKyRjbKgryt5uRrkKpPdJW8gUun5CoPEtNEQ6NT3vfI7DhjkiTevVxXkDHf0ENNtmhbla/3fYOB2jkJDYLOMyw2UTdn232ORlVHF0vVVjUZfJxrIUIb8L8XZ/dxXikORsY3Z0HYD8t6GDoAmvLr7LMw1pv3XxW6eV14Hc9SXoZdWwYTHYPQtT899pBrc7TqtLHh8OoQxMSFSfdiH7jfjkKB2VFUV7TNysxjg94ip9dC4R1tS49UHurP8CIBeMOyXFmlgiql5xU=
install:
- pip install -r requirements.txt
- pip install pylint circuitpython-build-tools Sphinx sphinx-rtd-theme
- pip install --force-reinstall pylint==1.9.2
script:
- pylint adafruit_am2320.py
- ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name,bad-whitespace examples/*.py)
- circuitpython-build-bundles --filename_prefix adafruit-circuitpython-am2320 --library_location .
- cd docs && sphinx-build -E -W -b html . _build/html && cd ..
