from setuptools import setup

setup(name='buzzword',
      version='1.0.1',  # DO NOT EDIT THIS LINE MANUALLY. LET bump2version UTILITY DO IT
      description='Sophisticated corpus linguistics',
      url='http://github.com/interrogator/buzzword',
      author='Daniel McDonald',
      include_package_data=True,
      zip_safe=False,
      packages=['buzzword'],
      scripts=['buzzword/scripts/buzzword-parse',
               'buzzword/scripts/buzzword',
               'buzzword/scripts/buzzword-build',
               'buzzword/scripts/buzzword-quickstart'],
      package_dir={'buzzword': 'buzzword'},
      author_email='mcddjx@gmail.com',
      license='MIT',
      keywords=['corpus', 'linguistics', 'nlp'],
      install_requires=['buzz',
                        'numpy',
                        'pandas',
                        'rumps',
                        'flask',
                        'Flask-Bootstrap',
                        'flask-nav',
                        'Flask-WTF',
                        'Werkzeug',
                        'WTForms'],
      dependency_links=['http://github.com/interrogator/rumps/tarball/master'])
