---
# This playbook provisions the google compute engine topology.

- name:  "schema check and Pre Provisioning Activities on topology_file"
  hosts: localhost
  gather_facts: True
  roles:
    - { role: 'common' }

- name:  "Provisioning openstack resources"
  hosts: localhost
  gather_facts: True
  roles:
    - { role: 'gcloud' }

- name: "Writing contents to file"
  hosts: localhost
  gather_facts: True
  roles:
    - { role: 'gather_resources' }
