---
# This playbook provisions the openstack topology.

- name:  "schema check and Pre-Provisioning Activities on topology_file"
  hosts: localhost
  gather_facts: True
  roles:
    - { role: 'common' }

- name:  "Provisioning openstack resources"
  hosts: localhost
  gather_facts: True
  roles:
    - { role: 'openstack' }

- name: "Gather resources to the RunDB"
  hosts: localhost
  gather_facts: True
  roles:
    - { role: 'gather_resources' }
