# coding: utf-8

"""
    Qc API

    QC API  # noqa: E501

    OpenAPI spec version: 2.0.3
    Contact: cloudsupport@telestream.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import telestream_cloud_qc
from telestream_cloud_qc.api.qc_api import QcApi  # noqa: E501
from telestream_cloud_qc.rest import ApiException


class TestQcApi(unittest.TestCase):
    """QcApi unit test stubs"""

    def setUp(self):
        self.api = telestream_cloud_qc.api.qc_api.QcApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_job(self):
        """Test case for cancel_job

        """
        pass

    def test_create_job(self):
        """Test case for create_job

        Create a new job  # noqa: E501
        """
        pass

    def test_create_project(self):
        """Test case for create_project

        Create a new project  # noqa: E501
        """
        pass

    def test_get_job(self):
        """Test case for get_job

        Get QC job  # noqa: E501
        """
        pass

    def test_get_project(self):
        """Test case for get_project

        Get project by Id  # noqa: E501
        """
        pass

    def test_import_template(self):
        """Test case for import_template

        Import Vidchecker template  # noqa: E501
        """
        pass

    def test_list_jobs(self):
        """Test case for list_jobs

        Get jobs form projects  # noqa: E501
        """
        pass

    def test_list_projects(self):
        """Test case for list_projects

        List all projects for an account  # noqa: E501
        """
        pass

    def test_modify_project(self):
        """Test case for modify_project

        Modify project  # noqa: E501
        """
        pass

    def test_proxy(self):
        """Test case for proxy

        """
        pass

    def test_remove_job(self):
        """Test case for remove_job

        """
        pass

    def test_remove_project(self):
        """Test case for remove_project

        """
        pass

    def test_signed_urls(self):
        """Test case for signed_urls

        """
        pass

    def test_templates(self):
        """Test case for templates

        List all templates  # noqa: E501
        """
        pass

    def test_upload_video(self):
        """Test case for upload_video

        Creates an upload session  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
