version: 2.1

executors:
  ubuntu-builder:
    docker:
      - image: trustlines/builder:master8
    working_directory: ~/repo

# define some common commands
# see https://circleci.com/docs/2.0/configuration-reference/#commands-requires-version-21
commands:
  create-venv:
    description: "Create venv"
    steps:
      - run:
          name: Create python venv
          command: |
            python3 -m venv venv
            venv/bin/pip install -c constraints.txt pip wheel setuptools

  config-path:
    description: "set environment variables and change PATH"
    steps:
    - run:
        name: Configuring PATH
        command: |
          echo >> ${BASH_ENV} 'export PATH=~/bin:~/repo/venv/bin:${PATH}'

jobs:
  build-sdist:
    executor: ubuntu-builder
    steps:
      - checkout
      - config-path
      - create-venv
      - run:
          name: Build distribution
          command: |
            python setup.py sdist
      - persist_to_workspace:
          root: "~"
          paths:
            - repo

  upload-pypi:
    executor: ubuntu-builder
    steps:
      - attach_workspace:
          at: '~'
      - config-path
      - run:
          name: Init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USER" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: Upload to pypi
          command: |
            twine upload dist/*

workflows:
  version: 2
  default:
    jobs:
      - build-sdist
          #filters:
           # branches:
            #  only:
             #   - master

      - upload-pypi:
          requires:
            - build-sdist
          #filters:
           # branches:
            #  only:
             #   - master
          context: pypi-credentials
