--- !ditz.rubyforge.org,2008-03-06/project 
name: PyDitz
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: PyDitz
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.1"
  status: :released
  release_time: 2013-11-23 00:10:48.045971 Z
  log_events: 
  - - 2010-04-09 14:35:19.190619 Z
    - Glenn Hutchings <zondo42@googlemail.com>
    - created
    - ""
  - - 2013-11-23 00:10:48.046045 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - released
    - It's good to go.
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.2"
  status: :released
  release_time: 2013-11-23 16:32:01.769636 Z
  log_events: 
  - - 2013-11-23 16:19:36.052722 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - created
    - Typical... just after release, then the bugs appear.
  - - 2013-11-23 16:32:01.769712 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - released
    - Let's try again...
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.3"
  status: :released
  release_time: 2013-11-23 22:54:28.305275 Z
  log_events: 
  - - 2013-11-23 21:15:49.429777 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - created
    - More bugs to fix...
  - - 2013-11-23 22:54:28.305348 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.4"
  status: :released
  release_time: 2013-12-09 19:10:58.456029 Z
  log_events: 
  - - 2013-12-01 15:48:02.236282 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - created
    - ""
  - - 2013-12-09 19:10:58.456039 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.5"
  status: :released
  release_time: 2013-12-12 22:10:19.535262 Z
  log_events: 
  - - 2013-12-09 19:14:18.575684 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - created
    - ""
  - - 2013-12-12 22:10:19.535285 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.5.1
  status: :released
  release_time: 2013-12-18 19:39:24.173187 Z
  log_events: 
  - - 2013-12-17 12:18:26.303039 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - created
    - ""
  - - 2013-12-18 19:39:24.173205 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.5.2
  status: :released
  release_time: 2013-12-20 19:32:31.424373 Z
  log_events: 
  - - 2013-12-19 12:02:31.276000 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - created
    - ""
  - - 2013-12-20 19:32:31.424391 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.6"
  status: :released
  release_time: 2014-03-28 17:23:05.076584 Z
  log_events: 
  - - 2013-12-12 14:20:15.078000 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - created
    - ""
  - - 2014-03-28 17:23:05.076604 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.6.1
  status: :released
  release_time: 2014-08-09 13:32:06.669782 Z
  log_events: 
  - - 2014-08-07 08:28:35.027103 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - created
    - ""
  - - 2014-08-09 13:32:06.669817 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.6.2
  status: :released
  release_time: 2014-08-10 14:46:58.821371 Z
  log_events: 
  - - 2014-08-09 15:17:33.439730 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - created
    - ""
  - - 2014-08-10 14:46:58.821389 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.7"
  status: :released
  release_time: 2014-09-28 12:35:05.644871 Z
  log_events: 
  - - 2014-08-14 10:55:12.389557 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - created
    - ""
  - - 2014-09-28 12:35:05.644917 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.8"
  status: :released
  release_time: 2014-12-05 14:03:16.774594 Z
  log_events: 
  - - 2014-09-29 13:37:59.129796 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - created
    - ""
  - - 2014-12-05 14:03:16.774801 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - released
    - It's good to go.
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.8.1
  status: :released
  release_time: 2015-08-18 20:04:48.748966 Z
  log_events: 
  - - 2015-03-20 08:43:11.917000 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - created
    - ""
  - - 2015-08-18 20:04:48.749037 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.9"
  status: :released
  release_time: 2015-09-27 10:44:33.497725 Z
  log_events: 
  - - 2014-12-05 13:41:32.510128 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - created
    - ""
  - - 2015-09-27 10:44:33.497748 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.9.1
  status: :released
  release_time: 2016-03-24 10:24:12.437560 Z
  log_events: 
  - - 2016-03-07 19:42:30.000155 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - created
    - ""
  - - 2016-03-24 10:24:12.437620 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.10"
  status: :released
  release_time: 2016-11-27 11:22:28.672392 Z
  log_events: 
  - - 2016-06-03 11:34:11.469636 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - created
    - ""
  - - 2016-11-27 11:22:28.672415 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.10.1
  status: :released
  release_time: 2017-07-31 17:43:39.170520 Z
  log_events: 
  - - 2017-03-19 19:54:49.255781 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - created
    - ""
  - - 2017-07-31 17:43:39.170539 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.10.2
  status: :released
  release_time: 2018-08-31 09:17:20.081149 Z
  log_events: 
  - - 2018-08-31 08:27:59.509149 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - created
    - ""
  - - 2018-08-31 09:17:20.081232 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.10.3
  status: :released
  release_time: 2019-01-11 15:56:55.659554 Z
  log_events: 
  - - 2019-01-11 15:49:45.347034 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - created
    - ""
  - - 2019-01-11 15:56:55.659579 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - released
    - ""
