
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-01-04T15:42:09-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "c962031c9a045d684da276a9f99fc8226bd01285",
 "version": "0.6.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
