# Contains parameters shared between multiple modules
# Note that this configuration file will be imported after the shared parameters config.
# For more, see overwatch.base.config
#
# author: Raymond Ehlers <raymond.ehlers@cern.ch>, Yale University
# date: 16 July 2018

# Set debug
debug: false
# Set the logging level.
loggingLevel: "INFO"
# Enable sending warning level logs via email.
emailLogger: False
# Determine where the emailed logs should be sent. There can be more than one recipient.
emailLoggerAddresses:
    - ""

# List of subsystems.
# Each subsystem listed here will have an individual page for their respective histograms.
# The HLT _MUST_ be included here!
subsystemList: &subsystemList
    - "EMC"
    - "TPC"
    - "HLT"

# Each of these subsystems will also get an individual page for access to their respective ROOT files.
subsystemsWithRootFilesToShow: *subsystemList

# Select whether to enable trending
trending: true

# Folders
# The name of the static folder on the disk.
staticFolder: &staticFolder "static"

# The name of the data folder on the disk.
dataFolder: &dataFolder "data"

# The name of the templates folder on the disk.
templateFolder: &templateFolder "templates"

# The path to the database.
databaseLocation: !joinPaths
    - "file://"
    - *dataFolder
    - "overwatch.fs"

# The file extension to use when printing ROOT files.
fileExtension: "png"

# Location of the receiver files.
receiverData: *dataFolder
# Temporary storage location for the receiver data files.
receiverDataTempStorage: !joinPaths
    - *dataFolder
    - "tempStorage"
dataTransferLocations:
    # Overwatch sites, where the data will be transferred via rsync.
    # Entries are of the form "siteName : path"
    # The values must be valid rsync paths (ie. "a@b:/path/to/dir")
    site1: ""
    # EOS. If "EOS" is in the name, we will transfer the files via EOS.
    EOS: "/eos/experiment/alice/overwatch/"
# Number of times we should try to transfer data when the transfer fails.
dataTransferRetries: 2
# Time in seconds to wait between checking for new files
dataTransferTimeToSleep: 20

# Data replay settings
# Time to sleep between each replay execution.
dataReplayTimeToSleep: 30
# Select which Run directory will be replayed. This must be the path to the full run directory.
# For example, it may be "data/Run123456". "Run" must be in the directory name.
# It is null be default because we don't want to unexpected begin replaying, which could lead to data loss.
dataReplaySourceDirectory: null
# Where the data should be replayed to. Usually, this is just the data folder, because Overwatch
# will then process the files from there.
dataReplayDestinationDirectory: !joinPaths
    - *dataFolder
# Location where directories and files are temporarily stored when replaying a run.
dataReplayTempStorageDirectory: !joinPaths
    - *dataFolder
    - "tempReplayData"
# Maximum number of files to move per replay.
# nMaxFiles set to one will ensure that files are transferred one by one, which is the desired behavior if one
# wants to test the evolution of dataset. Such an approach is the best possible simulation of actually receiving data.
dataReplayMaxFilesPerReplay: 1
