[tool.poetry]
name = "chatql"
version = "0.1.0"
readme = "README.md"
authors = ["katsugeneration <katsu.generation.888@gmail.com>"]
homepage = "https://github.com/katsugeneration"
homeprepositoryage = "https://github.com/katsugeneration/chatql"

[tool.poetry.dependencies]
python = "^3.6"
graphene = "^2.1"
mongoengine = "^0.16.3"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
nose = "^1.3"
tox = "^3.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
