[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "fluentxy"
author = "Bryan W. Weber"
author-email = "bryan.w.weber@gmail.com"
home-page = "https://github.com/bryanwweber/fluentxy"
classifiers = [
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3",
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3 :: Only",
]
requires = [
    "parse",
    "pandas",
    "numpy",
]
requires-python = "~=3.6"
description-file = "README.md"
